[project]
name = "tree-sitter-actions"
description = "parser for the actions file as defined by the specification therein"
version = "0.10.0"
keywords = ["actions", "incremental", "parsing", "tree-sitter"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Darrion Burgess", email = "darrionburgess@gmail.com" }]
requires-python = ">=3.10"
license.text = "MIT"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/clearheadtodo-devs/tree-sitter-actions"

[project.optional-dependencies]
core = ["tree-sitter~=0.26"]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
