(action_list
 (root_action
  (core_action
   (state 
    (not_started))
   (name))
  (child_action_list
   (child_action
    (child_icon)
    (core_action
     (state 
      (not_started))
     (name))
    (grandchild_action_list
     (grandchild_action
      (grandchild_icon)
      (core_action
       (state 
	(not_started))
       (name))
      (great_grandchild_action_list
       (great_grandchild_action
	(great_grandchild_icon)
	(core_action
	 (state 
	  (not_started))
	 (name))
	(double_great_grandchild_action_list
	 (double_great_grandchild_action
	  (double_great_grandchild_icon)
	  (core_action
	   (state 
	    (not_started))
	   (name))
	  (leaf_action_list
	   (leaf_action
	    (leaf_icon)
	    (core_action
	     (state 
	      (not_started))
	     (name))))))))))))))
