(action_list
 (root_action
  (core_action
   (state 
    (completed))
   (name)
   (do_date_or_time
    (do_date_icon)
    (extended_date_and_time
     (date_and_time
      (date
       (year)
       (month)
       (day))
      (time
       (hour)
       (minute)))
     (duration
      (duration_designator)
      (duration_value)))
    (recurrance
     (recurrance_icon)
     (recurrance_structure
      (daily_recurrance
       (time
	(hour)
	(minute)))))))))
