(source_file
  (root_action
    state: (state
      value: (state_completed))
    name: (name)
    metadata: (description)
    metadata: (priority)
    metadata: (story)
    metadata: (context
      tag: (tag)
      tag: (tag))
    metadata: (do_date
      datetime: (datetime)
      duration: (duration))
    metadata: (completed_date
      datetime: (datetime))
    metadata: (id)
    child: (depth1_action
      state: (state
        value: (state_not_started))
      name: (name)
      child: (depth2_action
        state: (state
          value: (state_not_started))
        name: (name)
        child: (depth3_action
          state: (state
            value: (state_not_started))
          name: (name)
          child: (depth4_action
            state: (state
              value: (state_not_started))
            name: (name)
            child: (depth5_action
              state: (state
                value: (state_not_started))
              name: (name))))))))