(action_list
 (root_action
  (core_action
   (state 
    (completed))
   (name)
   (description
    (description_text))
   (priority
    (priority_number))
   (context_list
    (context_icon)
    (middle_context
     (context_text)
     (context_separator))
    (context_text))
   (do_date_or_time
    (do_date_icon)
    (extended_date_and_time
     (date_and_time
      (date
       (year)
       (month)
       (day))
      (time
       (hour)
       (minute)))
     (duration
      (duration_designator)
      (duration_value))))
   (completed_date
    (date_and_time
     (date
      (year)
      (month)
      (day))
     (time
      (hour)
      (minute))))
	(id
	 (id_icon)
	 (uuid
	  (uuid_time_high)
	  (uuid_time_mid)
	  (uuid_version_random)
	  (uuid_variant_random)
	  (uuid_random))))
	(story
	 (story_icon)
	 (story_name))
	(child_action_list
	 (child_action
	  (child_icon)
	  (core_action
	   (state 
	    (not_started))
	   (name))
	  (grandchild_action_list
	   (grandchild_action
	    (grandchild_icon)
	    (core_action
	     (state 
	      (not_started))
	     (name))
	    (great_grandchild_action_list
	     (great_grandchild_action
	      (great_grandchild_icon)
	      (core_action
	       (state 
		(not_started))
	       (name))
	      (double_great_grandchild_action_list
	       (double_great_grandchild_action
		(double_great_grandchild_icon)
		(core_action
		 (state 
		  (not_started))
		 (name))
		(leaf_action_list
		 (leaf_action
		  (leaf_icon)
		  (core_action
		   (state 
		    (not_started))
		   (name))))))))))))))
