#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 144
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_child_icon = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  sym_not_started = 4,
  sym_completed = 5,
  anon_sym_DASH = 6,
  sym_blocked = 7,
  sym_cancelled = 8,
  sym_name = 9,
  aux_sym_description_token1 = 10,
  sym_desc_icon = 11,
  aux_sym_priority_token1 = 12,
  sym_priority_icon = 13,
  aux_sym_story_token1 = 14,
  sym_story_icon = 15,
  sym_context_icon = 16,
  aux_sym_middle_context_token1 = 17,
  sym_context_separator = 18,
  sym_do_date_icon = 19,
  anon_sym_PERCENT = 20,
  sym_year = 21,
  aux_sym_month_token1 = 22,
  anon_sym_COLON = 23,
  anon_sym_am = 24,
  anon_sym_pm = 25,
  anon_sym_AM = 26,
  anon_sym_PM = 27,
  sym_time_designator = 28,
  sym_duration_designator = 29,
  sym_id_icon = 30,
  sym_uuid_time_high = 31,
  sym_uuid_random = 32,
  sym_uuid_chunk = 33,
  sym_action_list = 34,
  sym_root_action = 35,
  sym_child_action_list = 36,
  sym_child_action = 37,
  sym_state = 38,
  sym_in_progress = 39,
  sym_description = 40,
  sym_priority = 41,
  sym_story = 42,
  sym_context_list = 43,
  sym_middle_context = 44,
  sym_tail_context = 45,
  sym_do_date_or_time = 46,
  sym_completed_date = 47,
  sym_date = 48,
  sym_month = 49,
  sym_day = 50,
  sym_time = 51,
  sym_hour = 52,
  sym_minute = 53,
  sym_duration = 54,
  sym_id = 55,
  sym_uuid = 56,
  sym_uuid_time_mid = 57,
  sym_uuid_version_random = 58,
  sym_uuid_variant_random = 59,
  aux_sym_action_list_repeat1 = 60,
  aux_sym_child_action_list_repeat1 = 61,
  aux_sym_context_list_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_child_icon] = "child_icon",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_not_started] = "not_started",
  [sym_completed] = "completed",
  [anon_sym_DASH] = "-",
  [sym_blocked] = "blocked",
  [sym_cancelled] = "cancelled",
  [sym_name] = "name",
  [aux_sym_description_token1] = "description_token1",
  [sym_desc_icon] = "desc_icon",
  [aux_sym_priority_token1] = "priority_token1",
  [sym_priority_icon] = "priority_icon",
  [aux_sym_story_token1] = "story_token1",
  [sym_story_icon] = "story_icon",
  [sym_context_icon] = "context_icon",
  [aux_sym_middle_context_token1] = "middle_context_token1",
  [sym_context_separator] = "context_separator",
  [sym_do_date_icon] = "do_date_icon",
  [anon_sym_PERCENT] = "%",
  [sym_year] = "year",
  [aux_sym_month_token1] = "month_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_am] = "am",
  [anon_sym_pm] = "pm",
  [anon_sym_AM] = "AM",
  [anon_sym_PM] = "PM",
  [sym_time_designator] = "time_designator",
  [sym_duration_designator] = "duration_designator",
  [sym_id_icon] = "id_icon",
  [sym_uuid_time_high] = "uuid_time_high",
  [sym_uuid_random] = "uuid_random",
  [sym_uuid_chunk] = "uuid_chunk",
  [sym_action_list] = "action_list",
  [sym_root_action] = "root_action",
  [sym_child_action_list] = "child_action_list",
  [sym_child_action] = "child_action",
  [sym_state] = "state",
  [sym_in_progress] = "in_progress",
  [sym_description] = "description",
  [sym_priority] = "priority",
  [sym_story] = "story",
  [sym_context_list] = "context_list",
  [sym_middle_context] = "middle_context",
  [sym_tail_context] = "tail_context",
  [sym_do_date_or_time] = "do_date_or_time",
  [sym_completed_date] = "completed_date",
  [sym_date] = "date",
  [sym_month] = "month",
  [sym_day] = "day",
  [sym_time] = "time",
  [sym_hour] = "hour",
  [sym_minute] = "minute",
  [sym_duration] = "duration",
  [sym_id] = "id",
  [sym_uuid] = "uuid",
  [sym_uuid_time_mid] = "uuid_time_mid",
  [sym_uuid_version_random] = "uuid_version_random",
  [sym_uuid_variant_random] = "uuid_variant_random",
  [aux_sym_action_list_repeat1] = "action_list_repeat1",
  [aux_sym_child_action_list_repeat1] = "child_action_list_repeat1",
  [aux_sym_context_list_repeat1] = "context_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_child_icon] = sym_child_icon,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_not_started] = sym_not_started,
  [sym_completed] = sym_completed,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_blocked] = sym_blocked,
  [sym_cancelled] = sym_cancelled,
  [sym_name] = sym_name,
  [aux_sym_description_token1] = aux_sym_description_token1,
  [sym_desc_icon] = sym_desc_icon,
  [aux_sym_priority_token1] = aux_sym_priority_token1,
  [sym_priority_icon] = sym_priority_icon,
  [aux_sym_story_token1] = aux_sym_story_token1,
  [sym_story_icon] = sym_story_icon,
  [sym_context_icon] = sym_context_icon,
  [aux_sym_middle_context_token1] = aux_sym_middle_context_token1,
  [sym_context_separator] = sym_context_separator,
  [sym_do_date_icon] = sym_do_date_icon,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_year] = sym_year,
  [aux_sym_month_token1] = aux_sym_month_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_am] = anon_sym_am,
  [anon_sym_pm] = anon_sym_pm,
  [anon_sym_AM] = anon_sym_AM,
  [anon_sym_PM] = anon_sym_PM,
  [sym_time_designator] = sym_time_designator,
  [sym_duration_designator] = sym_duration_designator,
  [sym_id_icon] = sym_id_icon,
  [sym_uuid_time_high] = sym_uuid_time_high,
  [sym_uuid_random] = sym_uuid_random,
  [sym_uuid_chunk] = sym_uuid_chunk,
  [sym_action_list] = sym_action_list,
  [sym_root_action] = sym_root_action,
  [sym_child_action_list] = sym_child_action_list,
  [sym_child_action] = sym_child_action,
  [sym_state] = sym_state,
  [sym_in_progress] = sym_in_progress,
  [sym_description] = sym_description,
  [sym_priority] = sym_priority,
  [sym_story] = sym_story,
  [sym_context_list] = sym_context_list,
  [sym_middle_context] = sym_middle_context,
  [sym_tail_context] = sym_tail_context,
  [sym_do_date_or_time] = sym_do_date_or_time,
  [sym_completed_date] = sym_completed_date,
  [sym_date] = sym_date,
  [sym_month] = sym_month,
  [sym_day] = sym_day,
  [sym_time] = sym_time,
  [sym_hour] = sym_hour,
  [sym_minute] = sym_minute,
  [sym_duration] = sym_duration,
  [sym_id] = sym_id,
  [sym_uuid] = sym_uuid,
  [sym_uuid_time_mid] = sym_uuid_time_mid,
  [sym_uuid_version_random] = sym_uuid_version_random,
  [sym_uuid_variant_random] = sym_uuid_variant_random,
  [aux_sym_action_list_repeat1] = aux_sym_action_list_repeat1,
  [aux_sym_child_action_list_repeat1] = aux_sym_child_action_list_repeat1,
  [aux_sym_context_list_repeat1] = aux_sym_context_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_child_icon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_not_started] = {
    .visible = true,
    .named = true,
  },
  [sym_completed] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_blocked] = {
    .visible = true,
    .named = true,
  },
  [sym_cancelled] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_description_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_desc_icon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_priority_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_priority_icon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_story_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_story_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_context_icon] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_middle_context_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_context_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_do_date_icon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_year] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_month_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_am] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PM] = {
    .visible = true,
    .named = false,
  },
  [sym_time_designator] = {
    .visible = true,
    .named = true,
  },
  [sym_duration_designator] = {
    .visible = true,
    .named = true,
  },
  [sym_id_icon] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid_time_high] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid_random] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_action_list] = {
    .visible = true,
    .named = true,
  },
  [sym_root_action] = {
    .visible = true,
    .named = true,
  },
  [sym_child_action_list] = {
    .visible = true,
    .named = true,
  },
  [sym_child_action] = {
    .visible = true,
    .named = true,
  },
  [sym_state] = {
    .visible = true,
    .named = true,
  },
  [sym_in_progress] = {
    .visible = true,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_story] = {
    .visible = true,
    .named = true,
  },
  [sym_context_list] = {
    .visible = true,
    .named = true,
  },
  [sym_middle_context] = {
    .visible = true,
    .named = true,
  },
  [sym_tail_context] = {
    .visible = true,
    .named = true,
  },
  [sym_do_date_or_time] = {
    .visible = true,
    .named = true,
  },
  [sym_completed_date] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_month] = {
    .visible = true,
    .named = true,
  },
  [sym_day] = {
    .visible = true,
    .named = true,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_hour] = {
    .visible = true,
    .named = true,
  },
  [sym_minute] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid_time_mid] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid_version_random] = {
    .visible = true,
    .named = true,
  },
  [sym_uuid_variant_random] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_action_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_child_action_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      if (lookahead == '!') ADVANCE(56);
      if (lookahead == '#') ADVANCE(74);
      if (lookahead == '$') ADVANCE(54);
      if (lookahead == '%') ADVANCE(64);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ')') ADVANCE(44);
      if (lookahead == '*') ADVANCE(59);
      if (lookahead == '+') ADVANCE(60);
      if (lookahead == ',') ADVANCE(62);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == ':') ADVANCE(67);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '>') ADVANCE(42);
      if (lookahead == '@') ADVANCE(63);
      if (lookahead == 'A') ADVANCE(4);
      if (lookahead == 'D') ADVANCE(73);
      if (lookahead == 'P') ADVANCE(5);
      if (lookahead == 'T') ADVANCE(72);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == 'a') ADVANCE(7);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '_') ADVANCE(49);
      if (lookahead == 'x') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == 'M') ADVANCE(70);
      END_STATE();
    case 5:
      if (lookahead == 'M') ADVANCE(71);
      END_STATE();
    case 6:
      if (lookahead == 'T') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'm') ADVANCE(68);
      END_STATE();
    case 8:
      if (lookahead == 'm') ADVANCE(69);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 10:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 11:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(58);
      END_STATE();
    case 12:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(53);
      END_STATE();
    case 13:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(51);
      END_STATE();
    case 14:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '#') ADVANCE(74);
      if (lookahead == '%') ADVANCE(64);
      if (lookahead == '(') ADVANCE(43);
      if (lookahead == ',') ADVANCE(62);
      if (lookahead == '>') ADVANCE(42);
      if (lookahead == '@') ADVANCE(63);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40)
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_child_icon);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_not_started);
      if (lookahead == ' ') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_completed);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_blocked);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_cancelled);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_name);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_description_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_description_token1);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_desc_icon);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_priority_icon);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_story_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_story_token1);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_story_icon);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_context_icon);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_middle_context_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_context_separator);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_do_date_icon);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_year);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_month_token1);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_am);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_pm);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_AM);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PM);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_time_designator);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_duration_designator);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_id_icon);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_uuid_time_high);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_uuid_random);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_uuid_chunk);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 40},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 40},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 40},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 9},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 9},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 9},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 10},
  [117] = {.lex_state = 6},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 9},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 11},
  [126] = {.lex_state = 14},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 12},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 13},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 3},
  [135] = {.lex_state = 3},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 14},
  [138] = {.lex_state = 13},
  [139] = {.lex_state = 13},
  [140] = {.lex_state = 3},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_child_icon] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_completed] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_blocked] = ACTIONS(1),
    [sym_cancelled] = ACTIONS(1),
    [sym_desc_icon] = ACTIONS(1),
    [aux_sym_priority_token1] = ACTIONS(1),
    [sym_priority_icon] = ACTIONS(1),
    [sym_story_icon] = ACTIONS(1),
    [sym_context_icon] = ACTIONS(1),
    [sym_context_separator] = ACTIONS(1),
    [sym_do_date_icon] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_year] = ACTIONS(1),
    [aux_sym_month_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_am] = ACTIONS(1),
    [anon_sym_pm] = ACTIONS(1),
    [anon_sym_AM] = ACTIONS(1),
    [anon_sym_PM] = ACTIONS(1),
    [sym_time_designator] = ACTIONS(1),
    [sym_duration_designator] = ACTIONS(1),
    [sym_id_icon] = ACTIONS(1),
  },
  [1] = {
    [sym_action_list] = STATE(136),
    [sym_root_action] = STATE(71),
    [sym_state] = STATE(138),
    [aux_sym_action_list_repeat1] = STATE(71),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(11), 1,
      sym_desc_icon,
    ACTIONS(13), 1,
      sym_priority_icon,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(3), 1,
      sym_description,
    STATE(6), 1,
      sym_priority,
    STATE(9), 1,
      sym_story,
    STATE(16), 1,
      sym_context_list,
    STATE(23), 1,
      sym_do_date_or_time,
    STATE(36), 1,
      sym_completed_date,
    STATE(55), 1,
      sym_id,
    STATE(97), 1,
      sym_child_action_list,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [57] = 16,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(13), 1,
      sym_priority_icon,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(5), 1,
      sym_priority,
    STATE(8), 1,
      sym_story,
    STATE(13), 1,
      sym_context_list,
    STATE(26), 1,
      sym_do_date_or_time,
    STATE(40), 1,
      sym_completed_date,
    STATE(58), 1,
      sym_id,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [108] = 15,
    ACTIONS(11), 1,
      sym_desc_icon,
    ACTIONS(13), 1,
      sym_priority_icon,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(7), 1,
      sym_description,
    STATE(11), 1,
      sym_priority,
    STATE(17), 1,
      sym_story,
    STATE(30), 1,
      sym_context_list,
    STATE(45), 1,
      sym_do_date_or_time,
    STATE(68), 1,
      sym_completed_date,
    STATE(85), 1,
      sym_id,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [156] = 14,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(10), 1,
      sym_story,
    STATE(15), 1,
      sym_context_list,
    STATE(27), 1,
      sym_do_date_or_time,
    STATE(41), 1,
      sym_completed_date,
    STATE(52), 1,
      sym_id,
    STATE(110), 1,
      sym_child_action_list,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [201] = 14,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(8), 1,
      sym_story,
    STATE(13), 1,
      sym_context_list,
    STATE(26), 1,
      sym_do_date_or_time,
    STATE(40), 1,
      sym_completed_date,
    STATE(58), 1,
      sym_id,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [246] = 13,
    ACTIONS(13), 1,
      sym_priority_icon,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(12), 1,
      sym_priority,
    STATE(19), 1,
      sym_story,
    STATE(31), 1,
      sym_context_list,
    STATE(47), 1,
      sym_do_date_or_time,
    STATE(69), 1,
      sym_completed_date,
    STATE(87), 1,
      sym_id,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [288] = 12,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(15), 1,
      sym_context_list,
    STATE(27), 1,
      sym_do_date_or_time,
    STATE(41), 1,
      sym_completed_date,
    STATE(52), 1,
      sym_id,
    STATE(110), 1,
      sym_child_action_list,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [327] = 12,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(13), 1,
      sym_context_list,
    STATE(26), 1,
      sym_do_date_or_time,
    STATE(40), 1,
      sym_completed_date,
    STATE(58), 1,
      sym_id,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [366] = 12,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(14), 1,
      sym_context_list,
    STATE(28), 1,
      sym_do_date_or_time,
    STATE(35), 1,
      sym_completed_date,
    STATE(54), 1,
      sym_id,
    STATE(98), 1,
      sym_child_action_list,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [405] = 11,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(19), 1,
      sym_story,
    STATE(31), 1,
      sym_context_list,
    STATE(47), 1,
      sym_do_date_or_time,
    STATE(69), 1,
      sym_completed_date,
    STATE(87), 1,
      sym_id,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [441] = 11,
    ACTIONS(15), 1,
      sym_story_icon,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(18), 1,
      sym_story,
    STATE(32), 1,
      sym_context_list,
    STATE(43), 1,
      sym_do_date_or_time,
    STATE(62), 1,
      sym_completed_date,
    STATE(96), 1,
      sym_id,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [477] = 10,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(27), 1,
      sym_do_date_or_time,
    STATE(41), 1,
      sym_completed_date,
    STATE(52), 1,
      sym_id,
    STATE(110), 1,
      sym_child_action_list,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [510] = 10,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(24), 1,
      sym_do_date_or_time,
    STATE(37), 1,
      sym_completed_date,
    STATE(51), 1,
      sym_id,
    STATE(100), 1,
      sym_child_action_list,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [543] = 10,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(28), 1,
      sym_do_date_or_time,
    STATE(35), 1,
      sym_completed_date,
    STATE(54), 1,
      sym_id,
    STATE(98), 1,
      sym_child_action_list,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [576] = 10,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(26), 1,
      sym_do_date_or_time,
    STATE(40), 1,
      sym_completed_date,
    STATE(58), 1,
      sym_id,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [609] = 9,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(31), 1,
      sym_context_list,
    STATE(47), 1,
      sym_do_date_or_time,
    STATE(69), 1,
      sym_completed_date,
    STATE(87), 1,
      sym_id,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [639] = 9,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(33), 1,
      sym_context_list,
    STATE(46), 1,
      sym_do_date_or_time,
    STATE(61), 1,
      sym_completed_date,
    STATE(78), 1,
      sym_id,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [669] = 9,
    ACTIONS(17), 1,
      sym_context_icon,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(32), 1,
      sym_context_list,
    STATE(43), 1,
      sym_do_date_or_time,
    STATE(62), 1,
      sym_completed_date,
    STATE(96), 1,
      sym_id,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [699] = 4,
    ACTIONS(45), 1,
      sym_duration_designator,
    STATE(67), 1,
      sym_duration,
    ACTIONS(43), 4,
      anon_sym_am,
      anon_sym_pm,
      anon_sym_AM,
      anon_sym_PM,
    ACTIONS(41), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [719] = 3,
    ACTIONS(49), 1,
      aux_sym_middle_context_token1,
    STATE(25), 3,
      sym_middle_context,
      sym_tail_context,
      aux_sym_context_list_repeat1,
    ACTIONS(47), 6,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [736] = 1,
    ACTIONS(51), 10,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      anon_sym_am,
      anon_sym_pm,
      anon_sym_AM,
      anon_sym_PM,
      sym_duration_designator,
      sym_id_icon,
  [749] = 8,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(40), 1,
      sym_completed_date,
    STATE(58), 1,
      sym_id,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [776] = 8,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(34), 1,
      sym_completed_date,
    STATE(59), 1,
      sym_id,
    STATE(115), 1,
      sym_child_action_list,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [803] = 3,
    ACTIONS(57), 1,
      aux_sym_middle_context_token1,
    STATE(25), 3,
      sym_middle_context,
      sym_tail_context,
      aux_sym_context_list_repeat1,
    ACTIONS(55), 6,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [820] = 8,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(41), 1,
      sym_completed_date,
    STATE(52), 1,
      sym_id,
    STATE(110), 1,
      sym_child_action_list,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [847] = 8,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(35), 1,
      sym_completed_date,
    STATE(54), 1,
      sym_id,
    STATE(98), 1,
      sym_child_action_list,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [874] = 8,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(37), 1,
      sym_completed_date,
    STATE(51), 1,
      sym_id,
    STATE(100), 1,
      sym_child_action_list,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [901] = 1,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      sym_priority_icon,
      sym_story_icon,
      sym_context_icon,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [913] = 7,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(47), 1,
      sym_do_date_or_time,
    STATE(69), 1,
      sym_completed_date,
    STATE(87), 1,
      sym_id,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [937] = 7,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(43), 1,
      sym_do_date_or_time,
    STATE(62), 1,
      sym_completed_date,
    STATE(96), 1,
      sym_id,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [961] = 7,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(46), 1,
      sym_do_date_or_time,
    STATE(61), 1,
      sym_completed_date,
    STATE(78), 1,
      sym_id,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [985] = 7,
    ACTIONS(19), 1,
      sym_do_date_icon,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(44), 1,
      sym_do_date_or_time,
    STATE(72), 1,
      sym_completed_date,
    STATE(83), 1,
      sym_id,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1009] = 6,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(56), 1,
      sym_id,
    STATE(113), 1,
      sym_child_action_list,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1030] = 6,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(51), 1,
      sym_id,
    STATE(100), 1,
      sym_child_action_list,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1051] = 6,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(58), 1,
      sym_id,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1072] = 6,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(59), 1,
      sym_id,
    STATE(115), 1,
      sym_child_action_list,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1093] = 1,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      sym_story_icon,
      sym_context_icon,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [1104] = 2,
    ACTIONS(70), 1,
      sym_context_separator,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      aux_sym_middle_context_token1,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [1117] = 6,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(52), 1,
      sym_id,
    STATE(110), 1,
      sym_child_action_list,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1138] = 6,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(54), 1,
      sym_id,
    STATE(98), 1,
      sym_child_action_list,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1159] = 3,
    ACTIONS(45), 1,
      sym_duration_designator,
    STATE(64), 1,
      sym_duration,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1173] = 5,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(61), 1,
      sym_completed_date,
    STATE(78), 1,
      sym_id,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1191] = 5,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(73), 1,
      sym_completed_date,
    STATE(81), 1,
      sym_id,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1209] = 5,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(69), 1,
      sym_completed_date,
    STATE(87), 1,
      sym_id,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1227] = 5,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(72), 1,
      sym_completed_date,
    STATE(83), 1,
      sym_id,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1245] = 5,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(62), 1,
      sym_completed_date,
    STATE(96), 1,
      sym_id,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1263] = 1,
    ACTIONS(76), 7,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      sym_context_icon,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [1273] = 1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      aux_sym_middle_context_token1,
      sym_do_date_icon,
      anon_sym_PERCENT,
      sym_id_icon,
  [1283] = 3,
    ACTIONS(82), 1,
      sym_time_designator,
    STATE(63), 1,
      sym_time,
    ACTIONS(80), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1297] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(115), 1,
      sym_child_action_list,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1312] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(98), 1,
      sym_child_action_list,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1327] = 1,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_time_designator,
      sym_id_icon,
  [1336] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(100), 1,
      sym_child_action_list,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1351] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(105), 1,
      sym_child_action_list,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1366] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(108), 1,
      sym_child_action_list,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1381] = 4,
    ACTIONS(88), 1,
      sym_not_started,
    ACTIONS(92), 1,
      anon_sym_DASH,
    STATE(132), 1,
      sym_in_progress,
    ACTIONS(90), 3,
      sym_completed,
      sym_blocked,
      sym_cancelled,
  [1396] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(110), 1,
      sym_child_action_list,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1411] = 4,
    ACTIONS(9), 1,
      sym_child_icon,
    STATE(113), 1,
      sym_child_action_list,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(74), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1426] = 3,
    ACTIONS(96), 1,
      sym_child_icon,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(60), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1438] = 3,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(83), 1,
      sym_id,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1450] = 3,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(78), 1,
      sym_id,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1462] = 1,
    ACTIONS(99), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1470] = 1,
    ACTIONS(101), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1478] = 1,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1486] = 4,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      anon_sym_LPAREN,
    STATE(138), 1,
      sym_state,
    STATE(66), 2,
      sym_root_action,
      aux_sym_action_list_repeat1,
  [1500] = 1,
    ACTIONS(72), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1508] = 3,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(87), 1,
      sym_id,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1520] = 3,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(96), 1,
      sym_id,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1532] = 1,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      anon_sym_PERCENT,
      sym_id_icon,
  [1540] = 4,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    STATE(138), 1,
      sym_state,
    STATE(66), 2,
      sym_root_action,
      aux_sym_action_list_repeat1,
  [1554] = 3,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(81), 1,
      sym_id,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1566] = 3,
    ACTIONS(23), 1,
      sym_id_icon,
    STATE(90), 1,
      sym_id,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1578] = 3,
    ACTIONS(9), 1,
      sym_child_icon,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
    STATE(60), 2,
      sym_child_action,
      aux_sym_child_action_list_repeat1,
  [1590] = 1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
      sym_id_icon,
  [1597] = 2,
    ACTIONS(49), 1,
      aux_sym_middle_context_token1,
    STATE(21), 3,
      sym_middle_context,
      sym_tail_context,
      aux_sym_context_list_repeat1,
  [1606] = 3,
    ACTIONS(82), 1,
      sym_time_designator,
    ACTIONS(120), 1,
      sym_year,
    STATE(70), 2,
      sym_date,
      sym_time,
  [1617] = 1,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1623] = 1,
    ACTIONS(122), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1629] = 3,
    ACTIONS(124), 1,
      anon_sym_DASH,
    ACTIONS(126), 1,
      sym_uuid_chunk,
    STATE(92), 1,
      sym_uuid_version_random,
  [1639] = 1,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1645] = 1,
    ACTIONS(128), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1651] = 1,
    ACTIONS(74), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1657] = 1,
    ACTIONS(130), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1663] = 1,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1669] = 3,
    ACTIONS(132), 1,
      anon_sym_DASH,
    ACTIONS(134), 1,
      sym_uuid_chunk,
    STATE(99), 1,
      sym_uuid_variant_random,
  [1679] = 1,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1685] = 1,
    ACTIONS(136), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1691] = 3,
    ACTIONS(126), 1,
      sym_uuid_chunk,
    ACTIONS(138), 1,
      anon_sym_DASH,
    STATE(86), 1,
      sym_uuid_version_random,
  [1701] = 1,
    ACTIONS(140), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1707] = 1,
    ACTIONS(142), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1713] = 3,
    ACTIONS(134), 1,
      sym_uuid_chunk,
    ACTIONS(144), 1,
      anon_sym_DASH,
    STATE(112), 1,
      sym_uuid_variant_random,
  [1723] = 3,
    ACTIONS(134), 1,
      sym_uuid_chunk,
    ACTIONS(146), 1,
      anon_sym_DASH,
    STATE(124), 1,
      sym_uuid_variant_random,
  [1733] = 1,
    ACTIONS(148), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1739] = 3,
    ACTIONS(150), 1,
      anon_sym_DASH,
    ACTIONS(152), 1,
      sym_uuid_chunk,
    STATE(89), 1,
      sym_uuid_time_mid,
  [1749] = 1,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      sym_child_icon,
      anon_sym_LPAREN,
  [1755] = 1,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1760] = 1,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1765] = 2,
    ACTIONS(154), 1,
      anon_sym_DASH,
    ACTIONS(156), 1,
      sym_uuid_random,
  [1772] = 1,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1777] = 2,
    ACTIONS(152), 1,
      sym_uuid_chunk,
    STATE(80), 1,
      sym_uuid_time_mid,
  [1784] = 2,
    ACTIONS(158), 1,
      aux_sym_month_token1,
    STATE(20), 1,
      sym_minute,
  [1791] = 2,
    ACTIONS(126), 1,
      sym_uuid_chunk,
    STATE(92), 1,
      sym_uuid_version_random,
  [1798] = 2,
    ACTIONS(160), 1,
      aux_sym_month_token1,
    STATE(143), 1,
      sym_month,
  [1805] = 1,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1810] = 2,
    ACTIONS(162), 1,
      aux_sym_month_token1,
    STATE(129), 1,
      sym_hour,
  [1817] = 1,
    ACTIONS(164), 2,
      anon_sym_DASH,
      sym_uuid_chunk,
  [1822] = 1,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1827] = 2,
    ACTIONS(168), 1,
      anon_sym_DASH,
    ACTIONS(170), 1,
      sym_uuid_random,
  [1834] = 1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1839] = 2,
    ACTIONS(134), 1,
      sym_uuid_chunk,
    STATE(124), 1,
      sym_uuid_variant_random,
  [1846] = 2,
    ACTIONS(172), 1,
      anon_sym_DASH,
    ACTIONS(174), 1,
      sym_uuid_random,
  [1853] = 1,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1858] = 2,
    ACTIONS(134), 1,
      sym_uuid_chunk,
    STATE(112), 1,
      sym_uuid_variant_random,
  [1865] = 1,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
  [1870] = 2,
    ACTIONS(176), 1,
      sym_uuid_time_high,
    STATE(94), 1,
      sym_uuid,
  [1877] = 2,
    ACTIONS(120), 1,
      sym_year,
    STATE(75), 1,
      sym_date,
  [1884] = 2,
    ACTIONS(126), 1,
      sym_uuid_chunk,
    STATE(93), 1,
      sym_uuid_version_random,
  [1891] = 1,
    ACTIONS(178), 2,
      anon_sym_DASH,
      sym_uuid_chunk,
  [1896] = 1,
    ACTIONS(180), 2,
      anon_sym_DASH,
      sym_uuid_random,
  [1901] = 2,
    ACTIONS(182), 1,
      aux_sym_month_token1,
    STATE(50), 1,
      sym_day,
  [1908] = 2,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    STATE(139), 1,
      sym_state,
  [1915] = 2,
    ACTIONS(134), 1,
      sym_uuid_chunk,
    STATE(109), 1,
      sym_uuid_variant_random,
  [1922] = 2,
    ACTIONS(184), 1,
      anon_sym_DASH,
    ACTIONS(186), 1,
      sym_uuid_random,
  [1929] = 1,
    ACTIONS(188), 1,
      aux_sym_story_token1,
  [1933] = 1,
    ACTIONS(190), 1,
      aux_sym_priority_token1,
  [1937] = 1,
    ACTIONS(186), 1,
      sym_uuid_random,
  [1941] = 1,
    ACTIONS(192), 1,
      aux_sym_description_token1,
  [1945] = 1,
    ACTIONS(194), 1,
      anon_sym_COLON,
  [1949] = 1,
    ACTIONS(196), 1,
      sym_name,
  [1953] = 1,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
  [1957] = 1,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
  [1961] = 1,
    ACTIONS(202), 1,
      anon_sym_DASH,
  [1965] = 1,
    ACTIONS(174), 1,
      sym_uuid_random,
  [1969] = 1,
    ACTIONS(170), 1,
      sym_uuid_random,
  [1973] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [1977] = 1,
    ACTIONS(206), 1,
      aux_sym_priority_token1,
  [1981] = 1,
    ACTIONS(208), 1,
      sym_name,
  [1985] = 1,
    ACTIONS(210), 1,
      sym_name,
  [1989] = 1,
    ACTIONS(212), 1,
      sym_uuid_random,
  [1993] = 1,
    ACTIONS(214), 1,
      anon_sym_DASH,
  [1997] = 1,
    ACTIONS(216), 1,
      anon_sym_COLON,
  [2001] = 1,
    ACTIONS(218), 1,
      anon_sym_DASH,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 156,
  [SMALL_STATE(6)] = 201,
  [SMALL_STATE(7)] = 246,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 327,
  [SMALL_STATE(10)] = 366,
  [SMALL_STATE(11)] = 405,
  [SMALL_STATE(12)] = 441,
  [SMALL_STATE(13)] = 477,
  [SMALL_STATE(14)] = 510,
  [SMALL_STATE(15)] = 543,
  [SMALL_STATE(16)] = 576,
  [SMALL_STATE(17)] = 609,
  [SMALL_STATE(18)] = 639,
  [SMALL_STATE(19)] = 669,
  [SMALL_STATE(20)] = 699,
  [SMALL_STATE(21)] = 719,
  [SMALL_STATE(22)] = 736,
  [SMALL_STATE(23)] = 749,
  [SMALL_STATE(24)] = 776,
  [SMALL_STATE(25)] = 803,
  [SMALL_STATE(26)] = 820,
  [SMALL_STATE(27)] = 847,
  [SMALL_STATE(28)] = 874,
  [SMALL_STATE(29)] = 901,
  [SMALL_STATE(30)] = 913,
  [SMALL_STATE(31)] = 937,
  [SMALL_STATE(32)] = 961,
  [SMALL_STATE(33)] = 985,
  [SMALL_STATE(34)] = 1009,
  [SMALL_STATE(35)] = 1030,
  [SMALL_STATE(36)] = 1051,
  [SMALL_STATE(37)] = 1072,
  [SMALL_STATE(38)] = 1093,
  [SMALL_STATE(39)] = 1104,
  [SMALL_STATE(40)] = 1117,
  [SMALL_STATE(41)] = 1138,
  [SMALL_STATE(42)] = 1159,
  [SMALL_STATE(43)] = 1173,
  [SMALL_STATE(44)] = 1191,
  [SMALL_STATE(45)] = 1209,
  [SMALL_STATE(46)] = 1227,
  [SMALL_STATE(47)] = 1245,
  [SMALL_STATE(48)] = 1263,
  [SMALL_STATE(49)] = 1273,
  [SMALL_STATE(50)] = 1283,
  [SMALL_STATE(51)] = 1297,
  [SMALL_STATE(52)] = 1312,
  [SMALL_STATE(53)] = 1327,
  [SMALL_STATE(54)] = 1336,
  [SMALL_STATE(55)] = 1351,
  [SMALL_STATE(56)] = 1366,
  [SMALL_STATE(57)] = 1381,
  [SMALL_STATE(58)] = 1396,
  [SMALL_STATE(59)] = 1411,
  [SMALL_STATE(60)] = 1426,
  [SMALL_STATE(61)] = 1438,
  [SMALL_STATE(62)] = 1450,
  [SMALL_STATE(63)] = 1462,
  [SMALL_STATE(64)] = 1470,
  [SMALL_STATE(65)] = 1478,
  [SMALL_STATE(66)] = 1486,
  [SMALL_STATE(67)] = 1500,
  [SMALL_STATE(68)] = 1508,
  [SMALL_STATE(69)] = 1520,
  [SMALL_STATE(70)] = 1532,
  [SMALL_STATE(71)] = 1540,
  [SMALL_STATE(72)] = 1554,
  [SMALL_STATE(73)] = 1566,
  [SMALL_STATE(74)] = 1578,
  [SMALL_STATE(75)] = 1590,
  [SMALL_STATE(76)] = 1597,
  [SMALL_STATE(77)] = 1606,
  [SMALL_STATE(78)] = 1617,
  [SMALL_STATE(79)] = 1623,
  [SMALL_STATE(80)] = 1629,
  [SMALL_STATE(81)] = 1639,
  [SMALL_STATE(82)] = 1645,
  [SMALL_STATE(83)] = 1651,
  [SMALL_STATE(84)] = 1657,
  [SMALL_STATE(85)] = 1663,
  [SMALL_STATE(86)] = 1669,
  [SMALL_STATE(87)] = 1679,
  [SMALL_STATE(88)] = 1685,
  [SMALL_STATE(89)] = 1691,
  [SMALL_STATE(90)] = 1701,
  [SMALL_STATE(91)] = 1707,
  [SMALL_STATE(92)] = 1713,
  [SMALL_STATE(93)] = 1723,
  [SMALL_STATE(94)] = 1733,
  [SMALL_STATE(95)] = 1739,
  [SMALL_STATE(96)] = 1749,
  [SMALL_STATE(97)] = 1755,
  [SMALL_STATE(98)] = 1760,
  [SMALL_STATE(99)] = 1765,
  [SMALL_STATE(100)] = 1772,
  [SMALL_STATE(101)] = 1777,
  [SMALL_STATE(102)] = 1784,
  [SMALL_STATE(103)] = 1791,
  [SMALL_STATE(104)] = 1798,
  [SMALL_STATE(105)] = 1805,
  [SMALL_STATE(106)] = 1810,
  [SMALL_STATE(107)] = 1817,
  [SMALL_STATE(108)] = 1822,
  [SMALL_STATE(109)] = 1827,
  [SMALL_STATE(110)] = 1834,
  [SMALL_STATE(111)] = 1839,
  [SMALL_STATE(112)] = 1846,
  [SMALL_STATE(113)] = 1853,
  [SMALL_STATE(114)] = 1858,
  [SMALL_STATE(115)] = 1865,
  [SMALL_STATE(116)] = 1870,
  [SMALL_STATE(117)] = 1877,
  [SMALL_STATE(118)] = 1884,
  [SMALL_STATE(119)] = 1891,
  [SMALL_STATE(120)] = 1896,
  [SMALL_STATE(121)] = 1901,
  [SMALL_STATE(122)] = 1908,
  [SMALL_STATE(123)] = 1915,
  [SMALL_STATE(124)] = 1922,
  [SMALL_STATE(125)] = 1929,
  [SMALL_STATE(126)] = 1933,
  [SMALL_STATE(127)] = 1937,
  [SMALL_STATE(128)] = 1941,
  [SMALL_STATE(129)] = 1945,
  [SMALL_STATE(130)] = 1949,
  [SMALL_STATE(131)] = 1953,
  [SMALL_STATE(132)] = 1957,
  [SMALL_STATE(133)] = 1961,
  [SMALL_STATE(134)] = 1965,
  [SMALL_STATE(135)] = 1969,
  [SMALL_STATE(136)] = 1973,
  [SMALL_STATE(137)] = 1977,
  [SMALL_STATE(138)] = 1981,
  [SMALL_STATE(139)] = 1985,
  [SMALL_STATE(140)] = 1989,
  [SMALL_STATE(141)] = 1993,
  [SMALL_STATE(142)] = 1997,
  [SMALL_STATE(143)] = 2001,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_list, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 4),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 5),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 6),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 6),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time, 4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context_list, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_minute, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 7),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_list_repeat1, 2),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_list_repeat1, 2), SHIFT_REPEAT(39),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 7),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_priority, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tail_context, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time, 5),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 8),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_story, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_middle_context, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date, 5),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_day, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 9),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_child_action_list_repeat1, 2),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_child_action_list_repeat1, 2), SHIFT_REPEAT(122),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_date, 6),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time, 6),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_duration, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_action_list_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_action_list_repeat1, 2), SHIFT_REPEAT(57),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_date_or_time, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action_list, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 9),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action_list, 1),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_date, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid, 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid, 7),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid, 6),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid, 9),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_action, 10),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid, 5),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid_version_random, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 10),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid_time_mid, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uuid_variant_random, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_progress, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_month, 1),
  [204] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hour, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_actions(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
