/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 10
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 20
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_GT = 1,
  anon_sym_GT_GT = 2,
  anon_sym_GT_GT_GT = 3,
  anon_sym_GT_GT_GT_GT = 4,
  anon_sym_GT_GT_GT_GT_GT = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  sym_state_not_started = 8,
  sym_state_completed = 9,
  sym_state_in_progress = 10,
  sym_state_blocked = 11,
  sym_state_cancelled = 12,
  sym_name = 13,
  anon_sym_DOLLAR = 14,
  aux_sym_description_token1 = 15,
  anon_sym_BANG = 16,
  aux_sym_priority_token1 = 17,
  anon_sym_STAR = 18,
  aux_sym_story_token1 = 19,
  anon_sym_PLUS = 20,
  anon_sym_COMMA = 21,
  sym_tag = 22,
  anon_sym_AT = 23,
  aux_sym_do_date_token1 = 24,
  anon_sym_PERCENT = 25,
  aux_sym_completed_date_token1 = 26,
  anon_sym_POUND = 27,
  aux_sym_id_token1 = 28,
  sym_source_file = 29,
  sym__action_body = 30,
  sym_root_action = 31,
  sym_depth1_action = 32,
  sym_depth2_action = 33,
  sym_depth3_action = 34,
  sym_depth4_action = 35,
  sym_depth5_action = 36,
  sym_state = 37,
  sym__metadata = 38,
  sym_description = 39,
  sym_priority = 40,
  sym_story = 41,
  sym_context = 42,
  sym_do_date = 43,
  sym_completed_date = 44,
  sym_id = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym__action_body_repeat1 = 47,
  aux_sym_root_action_repeat1 = 48,
  aux_sym_depth1_action_repeat1 = 49,
  aux_sym_depth2_action_repeat1 = 50,
  aux_sym_depth3_action_repeat1 = 51,
  aux_sym_depth4_action_repeat1 = 52,
  aux_sym_context_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_GT] = ">",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_GT_GT_GT] = ">>>",
  [anon_sym_GT_GT_GT_GT] = ">>>>",
  [anon_sym_GT_GT_GT_GT_GT] = ">>>>>",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_state_not_started] = "state_not_started",
  [sym_state_completed] = "state_completed",
  [sym_state_in_progress] = "state_in_progress",
  [sym_state_blocked] = "state_blocked",
  [sym_state_cancelled] = "state_cancelled",
  [sym_name] = "name",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_description_token1] = "description_token1",
  [anon_sym_BANG] = "!",
  [aux_sym_priority_token1] = "priority_token1",
  [anon_sym_STAR] = "*",
  [aux_sym_story_token1] = "story_token1",
  [anon_sym_PLUS] = "+",
  [anon_sym_COMMA] = ",",
  [sym_tag] = "tag",
  [anon_sym_AT] = "@",
  [aux_sym_do_date_token1] = "do_date_token1",
  [anon_sym_PERCENT] = "%",
  [aux_sym_completed_date_token1] = "completed_date_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_id_token1] = "id_token1",
  [sym_source_file] = "source_file",
  [sym__action_body] = "_action_body",
  [sym_root_action] = "root_action",
  [sym_depth1_action] = "depth1_action",
  [sym_depth2_action] = "depth2_action",
  [sym_depth3_action] = "depth3_action",
  [sym_depth4_action] = "depth4_action",
  [sym_depth5_action] = "depth5_action",
  [sym_state] = "state",
  [sym__metadata] = "_metadata",
  [sym_description] = "description",
  [sym_priority] = "priority",
  [sym_story] = "story",
  [sym_context] = "context",
  [sym_do_date] = "do_date",
  [sym_completed_date] = "completed_date",
  [sym_id] = "id",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__action_body_repeat1] = "_action_body_repeat1",
  [aux_sym_root_action_repeat1] = "root_action_repeat1",
  [aux_sym_depth1_action_repeat1] = "depth1_action_repeat1",
  [aux_sym_depth2_action_repeat1] = "depth2_action_repeat1",
  [aux_sym_depth3_action_repeat1] = "depth3_action_repeat1",
  [aux_sym_depth4_action_repeat1] = "depth4_action_repeat1",
  [aux_sym_context_repeat1] = "context_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_GT_GT_GT] = anon_sym_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT,
  [anon_sym_GT_GT_GT_GT_GT] = anon_sym_GT_GT_GT_GT_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_state_not_started] = sym_state_not_started,
  [sym_state_completed] = sym_state_completed,
  [sym_state_in_progress] = sym_state_in_progress,
  [sym_state_blocked] = sym_state_blocked,
  [sym_state_cancelled] = sym_state_cancelled,
  [sym_name] = sym_name,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_description_token1] = aux_sym_description_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_priority_token1] = aux_sym_priority_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_story_token1] = aux_sym_story_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_tag] = sym_tag,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_do_date_token1] = aux_sym_do_date_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_completed_date_token1] = aux_sym_completed_date_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_id_token1] = aux_sym_id_token1,
  [sym_source_file] = sym_source_file,
  [sym__action_body] = sym__action_body,
  [sym_root_action] = sym_root_action,
  [sym_depth1_action] = sym_depth1_action,
  [sym_depth2_action] = sym_depth2_action,
  [sym_depth3_action] = sym_depth3_action,
  [sym_depth4_action] = sym_depth4_action,
  [sym_depth5_action] = sym_depth5_action,
  [sym_state] = sym_state,
  [sym__metadata] = sym__metadata,
  [sym_description] = sym_description,
  [sym_priority] = sym_priority,
  [sym_story] = sym_story,
  [sym_context] = sym_context,
  [sym_do_date] = sym_do_date,
  [sym_completed_date] = sym_completed_date,
  [sym_id] = sym_id,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__action_body_repeat1] = aux_sym__action_body_repeat1,
  [aux_sym_root_action_repeat1] = aux_sym_root_action_repeat1,
  [aux_sym_depth1_action_repeat1] = aux_sym_depth1_action_repeat1,
  [aux_sym_depth2_action_repeat1] = aux_sym_depth2_action_repeat1,
  [aux_sym_depth3_action_repeat1] = aux_sym_depth3_action_repeat1,
  [aux_sym_depth4_action_repeat1] = aux_sym_depth4_action_repeat1,
  [aux_sym_context_repeat1] = aux_sym_context_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT_GT_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_state_not_started] = {
    .visible = true,
    .named = true,
  },
  [sym_state_completed] = {
    .visible = true,
    .named = true,
  },
  [sym_state_in_progress] = {
    .visible = true,
    .named = true,
  },
  [sym_state_blocked] = {
    .visible = true,
    .named = true,
  },
  [sym_state_cancelled] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_description_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_priority_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_story_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_do_date_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_completed_date_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_id_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__action_body] = {
    .visible = false,
    .named = true,
  },
  [sym_root_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth1_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth2_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth3_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth4_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth5_action] = {
    .visible = true,
    .named = true,
  },
  [sym_state] = {
    .visible = true,
    .named = true,
  },
  [sym__metadata] = {
    .visible = false,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_story] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_do_date] = {
    .visible = true,
    .named = true,
  },
  [sym_completed_date] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__action_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth1_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth2_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth3_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth4_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_child = 1,
  field_datetime = 2,
  field_level = 3,
  field_metadata = 4,
  field_name = 5,
  field_state = 6,
  field_tag = 7,
  field_text = 8,
  field_uuid = 9,
  field_value = 10,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_child] = "child",
  [field_datetime] = "datetime",
  [field_level] = "level",
  [field_metadata] = "metadata",
  [field_name] = "name",
  [field_state] = "state",
  [field_tag] = "tag",
  [field_text] = "text",
  [field_uuid] = "uuid",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 4},
  [4] = {.index = 8, .length = 2},
  [5] = {.index = 10, .length = 1},
  [6] = {.index = 11, .length = 3},
  [7] = {.index = 14, .length = 2},
  [8] = {.index = 16, .length = 1},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 20, .length = 4},
  [11] = {.index = 24, .length = 1},
  [12] = {.index = 25, .length = 1},
  [13] = {.index = 26, .length = 1},
  [14] = {.index = 27, .length = 1},
  [15] = {.index = 28, .length = 1},
  [16] = {.index = 29, .length = 1},
  [17] = {.index = 30, .length = 2},
  [18] = {.index = 32, .length = 2},
  [19] = {.index = 34, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_metadata, 0, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_state, 0, .inherited = true},
  [3] =
    {field_child, 0},
  [4] =
    {field_child, 1, .inherited = true},
    {field_metadata, 0, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_state, 0, .inherited = true},
  [8] =
    {field_name, 1},
    {field_state, 0},
  [10] =
    {field_value, 1},
  [11] =
    {field_metadata, 1, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_state, 1, .inherited = true},
  [14] =
    {field_child, 0, .inherited = true},
    {field_child, 1, .inherited = true},
  [16] =
    {field_metadata, 0},
  [17] =
    {field_metadata, 2, .inherited = true},
    {field_name, 1},
    {field_state, 0},
  [20] =
    {field_child, 2, .inherited = true},
    {field_metadata, 1, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_state, 1, .inherited = true},
  [24] =
    {field_text, 1},
  [25] =
    {field_level, 1},
  [26] =
    {field_name, 1},
  [27] =
    {field_tag, 1},
  [28] =
    {field_datetime, 1},
  [29] =
    {field_uuid, 1},
  [30] =
    {field_metadata, 0, .inherited = true},
    {field_metadata, 1, .inherited = true},
  [32] =
    {field_tag, 1},
    {field_tag, 2, .inherited = true},
  [34] =
    {field_tag, 0, .inherited = true},
    {field_tag, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 29,
        '#', 45,
        '$', 26,
        '%', 42,
        '*', 32,
        '+', 35,
        ',', 36,
        '-', 21,
        '=', 22,
        '>', 11,
        '@', 39,
        '[', 16,
        ']', 17,
        '_', 23,
        'x', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != ',' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(44);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '-') ADVANCE(20);
      if (lookahead == '=') ADVANCE(22);
      if (lookahead == '_') ADVANCE(23);
      if (lookahead == 'x') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(7);
      END_STATE();
    case 8:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      if (lookahead == '>') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT);
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT_GT_GT_GT_GT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_state_not_started);
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_state_completed);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_state_in_progress);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_state_in_progress);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_state_blocked);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_state_cancelled);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_description_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_description_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_story_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_story_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != ',' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != ',' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_do_date_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_do_date_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_completed_date_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_completed_date_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_id_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 9},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT] = ACTIONS(1),
    [anon_sym_GT_GT_GT_GT_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_state_completed] = ACTIONS(1),
    [sym_state_in_progress] = ACTIONS(1),
    [sym_state_blocked] = ACTIONS(1),
    [sym_state_cancelled] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_priority_token1] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [aux_sym_id_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym__action_body] = STATE(37),
    [sym_root_action] = STATE(29),
    [sym_state] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_PLUS,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      anon_sym_POUND,
    STATE(4), 1,
      aux_sym__action_body_repeat1,
    ACTIONS(7), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
    ACTIONS(9), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    STATE(11), 8,
      sym__metadata,
      sym_description,
      sym_priority,
      sym_story,
      sym_context,
      sym_do_date,
      sym_completed_date,
      sym_id,
  [46] = 11,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_PLUS,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      anon_sym_POUND,
    STATE(2), 1,
      aux_sym__action_body_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
    ACTIONS(27), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    STATE(11), 8,
      sym__metadata,
      sym_description,
      sym_priority,
      sym_story,
      sym_context,
      sym_do_date,
      sym_completed_date,
      sym_id,
  [92] = 11,
    ACTIONS(33), 1,
      anon_sym_DOLLAR,
    ACTIONS(36), 1,
      anon_sym_BANG,
    ACTIONS(39), 1,
      anon_sym_STAR,
    ACTIONS(42), 1,
      anon_sym_PLUS,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      anon_sym_PERCENT,
    ACTIONS(51), 1,
      anon_sym_POUND,
    STATE(4), 1,
      aux_sym__action_body_repeat1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
    ACTIONS(31), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    STATE(11), 8,
      sym__metadata,
      sym_description,
      sym_priority,
      sym_story,
      sym_context,
      sym_do_date,
      sym_completed_date,
      sym_id,
  [138] = 4,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    STATE(6), 1,
      aux_sym_context_repeat1,
    ACTIONS(56), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(54), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [163] = 4,
    ACTIONS(58), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_context_repeat1,
    ACTIONS(62), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(60), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [188] = 4,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(7), 1,
      aux_sym_context_repeat1,
    ACTIONS(66), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(64), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [213] = 2,
    ACTIONS(73), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(71), 11,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [233] = 2,
    ACTIONS(77), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [252] = 2,
    ACTIONS(81), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [271] = 2,
    ACTIONS(85), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [290] = 2,
    ACTIONS(89), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [309] = 2,
    ACTIONS(93), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(91), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [328] = 2,
    ACTIONS(97), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(95), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [347] = 2,
    ACTIONS(101), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
    ACTIONS(99), 10,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      anon_sym_POUND,
  [366] = 5,
    ACTIONS(107), 1,
      anon_sym_GT_GT_GT_GT_GT,
    STATE(16), 1,
      aux_sym_depth4_action_repeat1,
    STATE(26), 1,
      sym_depth5_action,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(105), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [386] = 5,
    ACTIONS(114), 1,
      anon_sym_GT_GT_GT_GT_GT,
    STATE(18), 1,
      aux_sym_depth4_action_repeat1,
    STATE(26), 1,
      sym_depth5_action,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(112), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [406] = 5,
    ACTIONS(114), 1,
      anon_sym_GT_GT_GT_GT_GT,
    STATE(16), 1,
      aux_sym_depth4_action_repeat1,
    STATE(26), 1,
      sym_depth5_action,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(118), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [426] = 5,
    ACTIONS(124), 1,
      anon_sym_GT_GT_GT_GT,
    STATE(20), 1,
      aux_sym_depth3_action_repeat1,
    STATE(27), 1,
      sym_depth4_action,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(122), 3,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [445] = 5,
    ACTIONS(124), 1,
      anon_sym_GT_GT_GT_GT,
    STATE(21), 1,
      aux_sym_depth3_action_repeat1,
    STATE(27), 1,
      sym_depth4_action,
    ACTIONS(126), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(128), 3,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [464] = 5,
    ACTIONS(134), 1,
      anon_sym_GT_GT_GT_GT,
    STATE(21), 1,
      aux_sym_depth3_action_repeat1,
    STATE(27), 1,
      sym_depth4_action,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(132), 3,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [483] = 2,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
    ACTIONS(139), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [495] = 5,
    ACTIONS(145), 1,
      anon_sym_GT_GT_GT,
    STATE(24), 1,
      aux_sym_depth2_action_repeat1,
    STATE(34), 1,
      sym_depth3_action,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(143), 2,
      anon_sym_GT,
      anon_sym_GT_GT,
  [513] = 5,
    ACTIONS(145), 1,
      anon_sym_GT_GT_GT,
    STATE(25), 1,
      aux_sym_depth2_action_repeat1,
    STATE(34), 1,
      sym_depth3_action,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(149), 2,
      anon_sym_GT,
      anon_sym_GT_GT,
  [531] = 5,
    ACTIONS(155), 1,
      anon_sym_GT_GT_GT,
    STATE(25), 1,
      aux_sym_depth2_action_repeat1,
    STATE(34), 1,
      sym_depth3_action,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    ACTIONS(153), 2,
      anon_sym_GT,
      anon_sym_GT_GT,
  [549] = 2,
    ACTIONS(158), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT_GT,
      anon_sym_LBRACK,
    ACTIONS(160), 4,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
      anon_sym_GT_GT_GT_GT,
  [561] = 2,
    ACTIONS(162), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT_GT,
      anon_sym_LBRACK,
    ACTIONS(164), 3,
      anon_sym_GT,
      anon_sym_GT_GT,
      anon_sym_GT_GT_GT,
  [572] = 5,
    ACTIONS(168), 1,
      anon_sym_GT,
    ACTIONS(170), 1,
      anon_sym_GT_GT,
    STATE(32), 1,
      aux_sym_depth1_action_repeat1,
    STATE(38), 1,
      sym_depth2_action,
    ACTIONS(166), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [589] = 5,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    STATE(37), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
    STATE(31), 2,
      sym_root_action,
      aux_sym_source_file_repeat1,
  [606] = 5,
    ACTIONS(176), 1,
      anon_sym_GT,
    ACTIONS(178), 1,
      anon_sym_GT_GT,
    STATE(30), 1,
      aux_sym_depth1_action_repeat1,
    STATE(38), 1,
      sym_depth2_action,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [623] = 5,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(183), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
    STATE(31), 2,
      sym_root_action,
      aux_sym_source_file_repeat1,
  [640] = 5,
    ACTIONS(170), 1,
      anon_sym_GT_GT,
    ACTIONS(188), 1,
      anon_sym_GT,
    STATE(30), 1,
      aux_sym_depth1_action_repeat1,
    STATE(38), 1,
      sym_depth2_action,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [657] = 4,
    ACTIONS(192), 1,
      anon_sym_GT,
    STATE(33), 1,
      aux_sym_root_action_repeat1,
    STATE(44), 1,
      sym_depth1_action,
    ACTIONS(190), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [671] = 2,
    ACTIONS(197), 2,
      anon_sym_GT,
      anon_sym_GT_GT,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT_GT,
      anon_sym_LBRACK,
  [681] = 2,
    ACTIONS(199), 1,
      sym_state_not_started,
    ACTIONS(201), 4,
      sym_state_completed,
      sym_state_in_progress,
      sym_state_blocked,
      sym_state_cancelled,
  [691] = 4,
    ACTIONS(205), 1,
      anon_sym_GT,
    STATE(33), 1,
      aux_sym_root_action_repeat1,
    STATE(44), 1,
      sym_depth1_action,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [705] = 4,
    ACTIONS(205), 1,
      anon_sym_GT,
    STATE(36), 1,
      aux_sym_root_action_repeat1,
    STATE(44), 1,
      sym_depth1_action,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [719] = 2,
    ACTIONS(211), 1,
      anon_sym_GT,
    ACTIONS(209), 3,
      ts_builtin_sym_end,
      anon_sym_GT_GT,
      anon_sym_LBRACK,
  [728] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    STATE(19), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
  [738] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    STATE(17), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
  [748] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    STATE(28), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
  [758] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    STATE(23), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
  [768] = 3,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    STATE(22), 1,
      sym__action_body,
    STATE(49), 1,
      sym_state,
  [778] = 1,
    ACTIONS(213), 3,
      ts_builtin_sym_end,
      anon_sym_GT,
      anon_sym_LBRACK,
  [784] = 1,
    ACTIONS(215), 1,
      sym_name,
  [788] = 1,
    ACTIONS(217), 1,
      aux_sym_priority_token1,
  [792] = 1,
    ACTIONS(219), 1,
      aux_sym_description_token1,
  [796] = 1,
    ACTIONS(221), 1,
      aux_sym_id_token1,
  [800] = 1,
    ACTIONS(223), 1,
      sym_name,
  [804] = 1,
    ACTIONS(225), 1,
      sym_tag,
  [808] = 1,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
  [812] = 1,
    ACTIONS(229), 1,
      aux_sym_completed_date_token1,
  [816] = 1,
    ACTIONS(231), 1,
      aux_sym_story_token1,
  [820] = 1,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
  [824] = 1,
    ACTIONS(235), 1,
      sym_tag,
  [828] = 1,
    ACTIONS(237), 1,
      aux_sym_do_date_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 163,
  [SMALL_STATE(7)] = 188,
  [SMALL_STATE(8)] = 213,
  [SMALL_STATE(9)] = 233,
  [SMALL_STATE(10)] = 252,
  [SMALL_STATE(11)] = 271,
  [SMALL_STATE(12)] = 290,
  [SMALL_STATE(13)] = 309,
  [SMALL_STATE(14)] = 328,
  [SMALL_STATE(15)] = 347,
  [SMALL_STATE(16)] = 366,
  [SMALL_STATE(17)] = 386,
  [SMALL_STATE(18)] = 406,
  [SMALL_STATE(19)] = 426,
  [SMALL_STATE(20)] = 445,
  [SMALL_STATE(21)] = 464,
  [SMALL_STATE(22)] = 483,
  [SMALL_STATE(23)] = 495,
  [SMALL_STATE(24)] = 513,
  [SMALL_STATE(25)] = 531,
  [SMALL_STATE(26)] = 549,
  [SMALL_STATE(27)] = 561,
  [SMALL_STATE(28)] = 572,
  [SMALL_STATE(29)] = 589,
  [SMALL_STATE(30)] = 606,
  [SMALL_STATE(31)] = 623,
  [SMALL_STATE(32)] = 640,
  [SMALL_STATE(33)] = 657,
  [SMALL_STATE(34)] = 671,
  [SMALL_STATE(35)] = 681,
  [SMALL_STATE(36)] = 691,
  [SMALL_STATE(37)] = 705,
  [SMALL_STATE(38)] = 719,
  [SMALL_STATE(39)] = 728,
  [SMALL_STATE(40)] = 738,
  [SMALL_STATE(41)] = 748,
  [SMALL_STATE(42)] = 758,
  [SMALL_STATE(43)] = 768,
  [SMALL_STATE(44)] = 778,
  [SMALL_STATE(45)] = 784,
  [SMALL_STATE(46)] = 788,
  [SMALL_STATE(47)] = 792,
  [SMALL_STATE(48)] = 796,
  [SMALL_STATE(49)] = 800,
  [SMALL_STATE(50)] = 804,
  [SMALL_STATE(51)] = 808,
  [SMALL_STATE(52)] = 812,
  [SMALL_STATE(53)] = 816,
  [SMALL_STATE(54)] = 820,
  [SMALL_STATE(55)] = 824,
  [SMALL_STATE(56)] = 828,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__action_body, 3, 0, 9),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__action_body, 3, 0, 9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__action_body, 2, 0, 4),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__action_body, 2, 0, 4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(47),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(46),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(53),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(55),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(56),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(52),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 17), SHIFT_REPEAT(48),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 2, 0, 14),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 2, 0, 14),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 3, 0, 18),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 3, 0, 18),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 19),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_context_repeat1, 2, 0, 19),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 19), SHIFT_REPEAT(50),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 14),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_context_repeat1, 2, 0, 14),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 2, 0, 11),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 2, 0, 11),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_story, 2, 0, 13),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_story, 2, 0, 13),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 1, 0, 8),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__action_body_repeat1, 1, 0, 8),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_priority, 2, 0, 12),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_priority, 2, 0, 12),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 2, 0, 16),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id, 2, 0, 16),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_date, 2, 0, 15),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_date, 2, 0, 15),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_date, 2, 0, 15),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_completed_date, 2, 0, 15),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth4_action_repeat1, 2, 0, 7),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth4_action_repeat1, 2, 0, 7),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth4_action_repeat1, 2, 0, 7), SHIFT_REPEAT(43),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth4_action, 2, 0, 6),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth4_action, 2, 0, 6),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth4_action, 3, 0, 10),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth4_action, 3, 0, 10),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth3_action, 2, 0, 6),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth3_action, 2, 0, 6),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth3_action, 3, 0, 10),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth3_action, 3, 0, 10),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth3_action_repeat1, 2, 0, 7),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth3_action_repeat1, 2, 0, 7),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth3_action_repeat1, 2, 0, 7), SHIFT_REPEAT(40),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth5_action, 2, 0, 6),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth5_action, 2, 0, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth2_action, 2, 0, 6),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth2_action, 2, 0, 6),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth2_action, 3, 0, 10),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth2_action, 3, 0, 10),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth2_action_repeat1, 2, 0, 7),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth2_action_repeat1, 2, 0, 7),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth2_action_repeat1, 2, 0, 7), SHIFT_REPEAT(39),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth4_action_repeat1, 1, 0, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth4_action_repeat1, 1, 0, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth3_action_repeat1, 1, 0, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth3_action_repeat1, 1, 0, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth1_action, 2, 0, 6),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth1_action, 2, 0, 6),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth1_action_repeat1, 2, 0, 7),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth1_action_repeat1, 2, 0, 7),
  [178] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth1_action_repeat1, 2, 0, 7), SHIFT_REPEAT(42),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth1_action, 3, 0, 10),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth1_action, 3, 0, 10),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_action_repeat1, 2, 0, 7),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_action_repeat1, 2, 0, 7), SHIFT_REPEAT(41),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth2_action_repeat1, 1, 0, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth2_action_repeat1, 1, 0, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 2, 0, 3),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 1, 0, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth1_action_repeat1, 1, 0, 2),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth1_action_repeat1, 1, 0, 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_action_repeat1, 1, 0, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state, 3, 0, 5),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [233] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_actions(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "actions",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
