/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 19
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 28
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_depth1_marker = 1,
  sym_depth2_marker = 2,
  sym_depth3_marker = 3,
  sym_depth4_marker = 4,
  sym_depth5_marker = 5,
  sym_state_open = 6,
  sym_state_close = 7,
  sym_state_not_started = 8,
  sym_state_completed = 9,
  sym_state_in_progress = 10,
  sym_state_blocked = 11,
  sym_state_cancelled = 12,
  sym_name_text_chunk = 13,
  anon_sym_DOLLAR = 14,
  sym_description_text_chunk = 15,
  anon_sym_LBRACK_LBRACK = 16,
  anon_sym_PIPE = 17,
  anon_sym_RBRACK_RBRACK = 18,
  aux_sym_link_text_token1 = 19,
  anon_sym_BANG = 20,
  aux_sym_priority_token1 = 21,
  anon_sym_STAR = 22,
  aux_sym_story_token1 = 23,
  anon_sym_PLUS = 24,
  anon_sym_COMMA = 25,
  sym_tag = 26,
  anon_sym_AT = 27,
  sym_datetime = 28,
  anon_sym_D = 29,
  anon_sym_R_COLON = 30,
  sym_rrule_content = 31,
  anon_sym_PERCENT = 32,
  sym_uuid_value = 33,
  sym_id_hash = 34,
  sym_source_file = 35,
  sym__action_body = 36,
  sym_root_action = 37,
  sym_depth1_action = 38,
  sym_depth2_action = 39,
  sym_depth3_action = 40,
  sym_depth4_action = 41,
  sym_depth5_action = 42,
  sym_state = 43,
  sym_name = 44,
  sym__metadata = 45,
  sym_description = 46,
  sym_link = 47,
  sym_link_text = 48,
  sym_link_url = 49,
  sym_priority = 50,
  sym_story = 51,
  sym_context = 52,
  sym_do_date = 53,
  sym_duration = 54,
  sym_minutes = 55,
  sym_recurrence = 56,
  sym_completed_date = 57,
  sym_id = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym__action_body_repeat1 = 60,
  aux_sym_root_action_repeat1 = 61,
  aux_sym_depth1_action_repeat1 = 62,
  aux_sym_depth2_action_repeat1 = 63,
  aux_sym_depth3_action_repeat1 = 64,
  aux_sym_depth4_action_repeat1 = 65,
  aux_sym_name_repeat1 = 66,
  aux_sym_description_repeat1 = 67,
  aux_sym_context_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_depth1_marker] = "depth1_marker",
  [sym_depth2_marker] = "depth2_marker",
  [sym_depth3_marker] = "depth3_marker",
  [sym_depth4_marker] = "depth4_marker",
  [sym_depth5_marker] = "depth5_marker",
  [sym_state_open] = "state_open",
  [sym_state_close] = "state_close",
  [sym_state_not_started] = "state_not_started",
  [sym_state_completed] = "state_completed",
  [sym_state_in_progress] = "state_in_progress",
  [sym_state_blocked] = "state_blocked",
  [sym_state_cancelled] = "state_cancelled",
  [sym_name_text_chunk] = "name_text_chunk",
  [anon_sym_DOLLAR] = "$",
  [sym_description_text_chunk] = "description_text_chunk",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [aux_sym_link_text_token1] = "link_text_token1",
  [anon_sym_BANG] = "!",
  [aux_sym_priority_token1] = "priority_token1",
  [anon_sym_STAR] = "*",
  [aux_sym_story_token1] = "story_token1",
  [anon_sym_PLUS] = "+",
  [anon_sym_COMMA] = ",",
  [sym_tag] = "tag",
  [anon_sym_AT] = "@",
  [sym_datetime] = "datetime",
  [anon_sym_D] = "D",
  [anon_sym_R_COLON] = "R:",
  [sym_rrule_content] = "rrule_content",
  [anon_sym_PERCENT] = "%",
  [sym_uuid_value] = "uuid_value",
  [sym_id_hash] = "id_hash",
  [sym_source_file] = "source_file",
  [sym__action_body] = "_action_body",
  [sym_root_action] = "root_action",
  [sym_depth1_action] = "depth1_action",
  [sym_depth2_action] = "depth2_action",
  [sym_depth3_action] = "depth3_action",
  [sym_depth4_action] = "depth4_action",
  [sym_depth5_action] = "depth5_action",
  [sym_state] = "state",
  [sym_name] = "name",
  [sym__metadata] = "_metadata",
  [sym_description] = "description",
  [sym_link] = "link",
  [sym_link_text] = "link_text",
  [sym_link_url] = "link_url",
  [sym_priority] = "priority",
  [sym_story] = "story",
  [sym_context] = "context",
  [sym_do_date] = "do_date",
  [sym_duration] = "duration",
  [sym_minutes] = "minutes",
  [sym_recurrence] = "recurrence",
  [sym_completed_date] = "completed_date",
  [sym_id] = "id",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__action_body_repeat1] = "_action_body_repeat1",
  [aux_sym_root_action_repeat1] = "root_action_repeat1",
  [aux_sym_depth1_action_repeat1] = "depth1_action_repeat1",
  [aux_sym_depth2_action_repeat1] = "depth2_action_repeat1",
  [aux_sym_depth3_action_repeat1] = "depth3_action_repeat1",
  [aux_sym_depth4_action_repeat1] = "depth4_action_repeat1",
  [aux_sym_name_repeat1] = "name_repeat1",
  [aux_sym_description_repeat1] = "description_repeat1",
  [aux_sym_context_repeat1] = "context_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_depth1_marker] = sym_depth1_marker,
  [sym_depth2_marker] = sym_depth2_marker,
  [sym_depth3_marker] = sym_depth3_marker,
  [sym_depth4_marker] = sym_depth4_marker,
  [sym_depth5_marker] = sym_depth5_marker,
  [sym_state_open] = sym_state_open,
  [sym_state_close] = sym_state_close,
  [sym_state_not_started] = sym_state_not_started,
  [sym_state_completed] = sym_state_completed,
  [sym_state_in_progress] = sym_state_in_progress,
  [sym_state_blocked] = sym_state_blocked,
  [sym_state_cancelled] = sym_state_cancelled,
  [sym_name_text_chunk] = sym_name_text_chunk,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_description_text_chunk] = sym_description_text_chunk,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [aux_sym_link_text_token1] = aux_sym_link_text_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [aux_sym_priority_token1] = aux_sym_priority_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_story_token1] = aux_sym_story_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_tag] = sym_tag,
  [anon_sym_AT] = anon_sym_AT,
  [sym_datetime] = sym_datetime,
  [anon_sym_D] = anon_sym_D,
  [anon_sym_R_COLON] = anon_sym_R_COLON,
  [sym_rrule_content] = sym_rrule_content,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_uuid_value] = sym_uuid_value,
  [sym_id_hash] = sym_id_hash,
  [sym_source_file] = sym_source_file,
  [sym__action_body] = sym__action_body,
  [sym_root_action] = sym_root_action,
  [sym_depth1_action] = sym_depth1_action,
  [sym_depth2_action] = sym_depth2_action,
  [sym_depth3_action] = sym_depth3_action,
  [sym_depth4_action] = sym_depth4_action,
  [sym_depth5_action] = sym_depth5_action,
  [sym_state] = sym_state,
  [sym_name] = sym_name,
  [sym__metadata] = sym__metadata,
  [sym_description] = sym_description,
  [sym_link] = sym_link,
  [sym_link_text] = sym_link_text,
  [sym_link_url] = sym_link_url,
  [sym_priority] = sym_priority,
  [sym_story] = sym_story,
  [sym_context] = sym_context,
  [sym_do_date] = sym_do_date,
  [sym_duration] = sym_duration,
  [sym_minutes] = sym_minutes,
  [sym_recurrence] = sym_recurrence,
  [sym_completed_date] = sym_completed_date,
  [sym_id] = sym_id,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__action_body_repeat1] = aux_sym__action_body_repeat1,
  [aux_sym_root_action_repeat1] = aux_sym_root_action_repeat1,
  [aux_sym_depth1_action_repeat1] = aux_sym_depth1_action_repeat1,
  [aux_sym_depth2_action_repeat1] = aux_sym_depth2_action_repeat1,
  [aux_sym_depth3_action_repeat1] = aux_sym_depth3_action_repeat1,
  [aux_sym_depth4_action_repeat1] = aux_sym_depth4_action_repeat1,
  [aux_sym_name_repeat1] = aux_sym_name_repeat1,
  [aux_sym_description_repeat1] = aux_sym_description_repeat1,
  [aux_sym_context_repeat1] = aux_sym_context_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_depth1_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_depth2_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_depth3_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_depth4_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_depth5_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_state_open] = {
    .visible = true,
    .named = true,
  },
  [sym_state_close] = {
    .visible = true,
    .named = true,
  },
  [sym_state_not_started] = {
    .visible = true,
    .named = true,
  },
  [sym_state_completed] = {
    .visible = true,
    .named = true,
  },
  [sym_state_in_progress] = {
    .visible = true,
    .named = true,
  },
  [sym_state_blocked] = {
    .visible = true,
    .named = true,
  },
  [sym_state_cancelled] = {
    .visible = true,
    .named = true,
  },
  [sym_name_text_chunk] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_description_text_chunk] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_priority_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_story_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_datetime] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_D] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_R_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_rrule_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_uuid_value] = {
    .visible = true,
    .named = true,
  },
  [sym_id_hash] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__action_body] = {
    .visible = false,
    .named = true,
  },
  [sym_root_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth1_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth2_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth3_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth4_action] = {
    .visible = true,
    .named = true,
  },
  [sym_depth5_action] = {
    .visible = true,
    .named = true,
  },
  [sym_state] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__metadata] = {
    .visible = false,
    .named = true,
  },
  [sym_description] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym_link_url] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [sym_story] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_do_date] = {
    .visible = true,
    .named = true,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [sym_minutes] = {
    .visible = true,
    .named = true,
  },
  [sym_recurrence] = {
    .visible = true,
    .named = true,
  },
  [sym_completed_date] = {
    .visible = true,
    .named = true,
  },
  [sym_id] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__action_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_root_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth1_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth2_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth3_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_depth4_action_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_description_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_child = 1,
  field_close = 2,
  field_datetime = 3,
  field_duration = 4,
  field_icon = 5,
  field_level = 6,
  field_marker = 7,
  field_metadata = 8,
  field_minutes = 9,
  field_name = 10,
  field_open = 11,
  field_recurrence = 12,
  field_rrule = 13,
  field_state = 14,
  field_tag = 15,
  field_text = 16,
  field_url = 17,
  field_uuid = 18,
  field_value = 19,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_child] = "child",
  [field_close] = "close",
  [field_datetime] = "datetime",
  [field_duration] = "duration",
  [field_icon] = "icon",
  [field_level] = "level",
  [field_marker] = "marker",
  [field_metadata] = "metadata",
  [field_minutes] = "minutes",
  [field_name] = "name",
  [field_open] = "open",
  [field_recurrence] = "recurrence",
  [field_rrule] = "rrule",
  [field_state] = "state",
  [field_tag] = "tag",
  [field_text] = "text",
  [field_url] = "url",
  [field_uuid] = "uuid",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 4},
  [4] = {.index = 8, .length = 2},
  [5] = {.index = 10, .length = 3},
  [6] = {.index = 13, .length = 4},
  [7] = {.index = 17, .length = 2},
  [8] = {.index = 19, .length = 1},
  [9] = {.index = 20, .length = 3},
  [10] = {.index = 23, .length = 5},
  [11] = {.index = 28, .length = 1},
  [12] = {.index = 29, .length = 2},
  [13] = {.index = 31, .length = 2},
  [14] = {.index = 33, .length = 2},
  [15] = {.index = 35, .length = 2},
  [16] = {.index = 37, .length = 2},
  [17] = {.index = 39, .length = 2},
  [18] = {.index = 41, .length = 2},
  [19] = {.index = 43, .length = 3},
  [20] = {.index = 46, .length = 3},
  [21] = {.index = 49, .length = 3},
  [22] = {.index = 52, .length = 2},
  [23] = {.index = 54, .length = 1},
  [24] = {.index = 55, .length = 2},
  [25] = {.index = 57, .length = 1},
  [26] = {.index = 58, .length = 1},
  [27] = {.index = 59, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_metadata, 0, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_state, 0, .inherited = true},
  [3] =
    {field_child, 0},
  [4] =
    {field_child, 1, .inherited = true},
    {field_metadata, 0, .inherited = true},
    {field_name, 0, .inherited = true},
    {field_state, 0, .inherited = true},
  [8] =
    {field_name, 1},
    {field_state, 0},
  [10] =
    {field_close, 2},
    {field_open, 0},
    {field_value, 1},
  [13] =
    {field_marker, 0},
    {field_metadata, 1, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_state, 1, .inherited = true},
  [17] =
    {field_child, 0, .inherited = true},
    {field_child, 1, .inherited = true},
  [19] =
    {field_metadata, 0},
  [20] =
    {field_metadata, 2, .inherited = true},
    {field_name, 1},
    {field_state, 0},
  [23] =
    {field_child, 2, .inherited = true},
    {field_marker, 0},
    {field_metadata, 1, .inherited = true},
    {field_name, 1, .inherited = true},
    {field_state, 1, .inherited = true},
  [28] =
    {field_url, 1},
  [29] =
    {field_icon, 0},
    {field_text, 1},
  [31] =
    {field_icon, 0},
    {field_level, 1},
  [33] =
    {field_icon, 0},
    {field_name, 1},
  [35] =
    {field_icon, 0},
    {field_tag, 1},
  [37] =
    {field_datetime, 1},
    {field_icon, 0},
  [39] =
    {field_icon, 0},
    {field_uuid, 1},
  [41] =
    {field_metadata, 0, .inherited = true},
    {field_metadata, 1, .inherited = true},
  [43] =
    {field_icon, 0},
    {field_tag, 1},
    {field_tag, 2, .inherited = true},
  [46] =
    {field_datetime, 1},
    {field_duration, 2},
    {field_icon, 0},
  [49] =
    {field_datetime, 1},
    {field_icon, 0},
    {field_recurrence, 2},
  [52] =
    {field_text, 1},
    {field_url, 3},
  [54] =
    {field_tag, 1},
  [55] =
    {field_tag, 0, .inherited = true},
    {field_tag, 1, .inherited = true},
  [57] =
    {field_minutes, 1},
  [58] =
    {field_rrule, 1},
  [59] =
    {field_datetime, 1},
    {field_duration, 2},
    {field_icon, 0},
    {field_recurrence, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 14,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 55,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 65,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 71,
  [81] = 81,
  [82] = 79,
  [83] = 81,
};

static const TSCharacterRange sym_description_text_chunk_character_set_1[] = {
  {0, '\t'}, {0x0b, ' '}, {'"', '"'}, {'$', '$'}, {'&', ')'}, {',', '='}, {'?', '?'}, {'A', 'Z'},
  {'\\', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(68);
      ADVANCE_MAP(
        '!', 93,
        '#', 119,
        '$', 83,
        '%', 117,
        '*', 99,
        '+', 102,
        ',', 103,
        '-', 78,
        '=', 79,
        '>', 69,
        '@', 106,
        'D', 112,
        'F', 33,
        'R', 7,
        '[', 74,
        ']', 75,
        '_', 80,
        'x', 77,
        '|', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '[') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != '*' &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(87);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '*' &&
          lookahead != ',' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(105);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(101);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(76);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '=') ADVANCE(79);
      if (lookahead == '_') ADVANCE(80);
      if (lookahead == 'x') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(54);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(55);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(113);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(57);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'A') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'A') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'C') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'D') ADVANCE(11);
      if (lookahead == 'H') ADVANCE(30);
      if (lookahead == 'M') ADVANCE(23);
      if (lookahead == 'S') ADVANCE(17);
      if (lookahead == 'W') ADVANCE(21);
      if (lookahead == 'Y') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'D') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'H') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(29);
      if (lookahead == 'O') ADVANCE(27);
      END_STATE();
    case 24:
      if (lookahead == 'I') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 'K') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 'L') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'N') ADVANCE(35);
      END_STATE();
    case 28:
      if (lookahead == 'N') ADVANCE(15);
      END_STATE();
    case 29:
      if (lookahead == 'N') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'O') ADVANCE(37);
      END_STATE();
    case 31:
      if (lookahead == 'O') ADVANCE(28);
      END_STATE();
    case 32:
      if (lookahead == 'Q') ADVANCE(10);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(16);
      END_STATE();
    case 34:
      if (lookahead == 'R') ADVANCE(26);
      END_STATE();
    case 35:
      if (lookahead == 'T') ADVANCE(22);
      END_STATE();
    case 36:
      if (lookahead == 'T') ADVANCE(18);
      END_STATE();
    case 37:
      if (lookahead == 'U') ADVANCE(34);
      END_STATE();
    case 38:
      if (lookahead == 'U') ADVANCE(36);
      END_STATE();
    case 39:
      if (lookahead == 'Y') ADVANCE(114);
      END_STATE();
    case 40:
      if (lookahead == '[') ADVANCE(88);
      END_STATE();
    case 41:
      if (lookahead == ']') ADVANCE(42);
      if (lookahead == '|') ADVANCE(89);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 42:
      if (lookahead == ']') ADVANCE(90);
      END_STATE();
    case 43:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(92);
      END_STATE();
    case 44:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 45:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(45);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(118);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(107);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(108);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 64:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(115);
      END_STATE();
    case 65:
      if (('+' <= lookahead && lookahead <= '-') ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(116);
      END_STATE();
    case 66:
      if (eof) ADVANCE(68);
      if (lookahead == '\n') SKIP(66);
      if (lookahead == '!') ADVANCE(93);
      if (lookahead == '#') ADVANCE(119);
      if (lookahead == '$') ADVANCE(84);
      if (lookahead == '%') ADVANCE(117);
      if (lookahead == '*') ADVANCE(99);
      if (lookahead == '+') ADVANCE(102);
      if (lookahead == '>') ADVANCE(69);
      if (lookahead == '@') ADVANCE(106);
      if (lookahead == '[') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 67:
      if (eof) ADVANCE(68);
      if (lookahead == '\n') SKIP(67);
      if (lookahead == '!') ADVANCE(93);
      if (lookahead == '#') ADVANCE(119);
      if (lookahead == '$') ADVANCE(83);
      if (lookahead == '%') ADVANCE(117);
      if (lookahead == '*') ADVANCE(99);
      if (lookahead == '+') ADVANCE(102);
      if (lookahead == '>') ADVANCE(69);
      if (lookahead == '@') ADVANCE(106);
      if (lookahead == '[') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_depth1_marker);
      if (lookahead == '>') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_depth2_marker);
      if (lookahead == '>') ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_depth3_marker);
      if (lookahead == '>') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_depth4_marker);
      if (lookahead == '>') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_depth5_marker);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_state_open);
      if (lookahead == '[') ADVANCE(88);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_state_close);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_state_not_started);
      if (lookahead == ' ') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_state_completed);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_state_in_progress);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_state_blocked);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_state_cancelled);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_name_text_chunk);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(81);
      if (((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead))) &&
          lookahead != '$') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_name_text_chunk);
      if (((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead))) &&
          lookahead != '$') ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if ((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead))) ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_description_text_chunk);
      if (lookahead == '$') ADVANCE(84);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(85);
      if ((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead))) ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_description_text_chunk);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if ((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead))) ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_description_text_chunk);
      if ((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead))) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_link_text_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_link_text_token1);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (lookahead == '-') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_priority_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_story_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(101);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_story_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          (lookahead < '#' || '%' < lookahead) &&
          lookahead != '+' &&
          lookahead != '>' &&
          lookahead != '@') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead)) ||
          lookahead == '+' ||
          lookahead == '[') &&
          lookahead != '$' &&
          lookahead != ',') ADVANCE(105);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_tag);
      if (((!eof && set_contains(sym_description_text_chunk_character_set_1, 9, lookahead)) ||
          lookahead == '+' ||
          lookahead == '[') &&
          lookahead != '$' &&
          lookahead != ',') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_datetime);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == '.') ADVANCE(52);
      if (lookahead == 'Z') ADVANCE(107);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(59);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == ':') ADVANCE(58);
      if (lookahead == 'Z') ADVANCE(107);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(59);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == 'T') ADVANCE(56);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_datetime);
      if (lookahead == 'Z') ADVANCE(107);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_D);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_R_COLON);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_rrule_content);
      if (lookahead == ';') ADVANCE(64);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_rrule_content);
      if (lookahead == ';') ADVANCE(64);
      if (lookahead == '=') ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_rrule_content);
      if (lookahead == ';') ADVANCE(64);
      if (('+' <= lookahead && lookahead <= '-') ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_uuid_value);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_id_hash);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 66},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 66},
  [8] = {.lex_state = 67},
  [9] = {.lex_state = 67},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 67},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 67},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 66},
  [17] = {.lex_state = 66},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 67},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 43},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 43},
  [62] = {.lex_state = 41},
  [63] = {.lex_state = 41},
  [64] = {.lex_state = 67},
  [65] = {.lex_state = 43},
  [66] = {.lex_state = 43},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 41},
  [71] = {.lex_state = 41},
  [72] = {.lex_state = 41},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 44},
  [76] = {.lex_state = 44},
  [77] = {.lex_state = 45},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 41},
  [80] = {.lex_state = 41},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 41},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_depth1_marker] = ACTIONS(1),
    [sym_depth2_marker] = ACTIONS(1),
    [sym_depth3_marker] = ACTIONS(1),
    [sym_depth4_marker] = ACTIONS(1),
    [sym_depth5_marker] = ACTIONS(1),
    [sym_state_open] = ACTIONS(1),
    [sym_state_close] = ACTIONS(1),
    [sym_state_completed] = ACTIONS(1),
    [sym_state_in_progress] = ACTIONS(1),
    [sym_state_blocked] = ACTIONS(1),
    [sym_state_cancelled] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [aux_sym_priority_token1] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_datetime] = ACTIONS(1),
    [anon_sym_D] = ACTIONS(1),
    [anon_sym_R_COLON] = ACTIONS(1),
    [sym_rrule_content] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_id_hash] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(68),
    [sym__action_body] = STATE(51),
    [sym_root_action] = STATE(45),
    [sym_state] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(45),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_state_open] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_PLUS,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_hash,
    STATE(3), 1,
      aux_sym__action_body_repeat1,
    ACTIONS(7), 3,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
    ACTIONS(9), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    STATE(25), 8,
      sym__metadata,
      sym_description,
      sym_priority,
      sym_story,
      sym_context,
      sym_do_date,
      sym_completed_date,
      sym_id,
  [46] = 11,
    ACTIONS(11), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(17), 1,
      anon_sym_PLUS,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(21), 1,
      anon_sym_PERCENT,
    ACTIONS(23), 1,
      sym_id_hash,
    STATE(4), 1,
      aux_sym__action_body_repeat1,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
    ACTIONS(27), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    STATE(25), 8,
      sym__metadata,
      sym_description,
      sym_priority,
      sym_story,
      sym_context,
      sym_do_date,
      sym_completed_date,
      sym_id,
  [92] = 11,
    ACTIONS(33), 1,
      anon_sym_DOLLAR,
    ACTIONS(36), 1,
      anon_sym_BANG,
    ACTIONS(39), 1,
      anon_sym_STAR,
    ACTIONS(42), 1,
      anon_sym_PLUS,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      anon_sym_PERCENT,
    ACTIONS(51), 1,
      sym_id_hash,
    STATE(4), 1,
      aux_sym__action_body_repeat1,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
    ACTIONS(31), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    STATE(25), 8,
      sym__metadata,
      sym_description,
      sym_priority,
      sym_story,
      sym_context,
      sym_do_date,
      sym_completed_date,
      sym_id,
  [138] = 5,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      sym_description_text_chunk,
    ACTIONS(61), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(5), 2,
      sym_link,
      aux_sym_description_repeat1,
    ACTIONS(56), 13,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [167] = 6,
    ACTIONS(68), 1,
      anon_sym_D,
    ACTIONS(70), 1,
      anon_sym_R_COLON,
    STATE(12), 1,
      sym_duration,
    STATE(26), 1,
      sym_recurrence,
    ACTIONS(66), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(64), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [198] = 5,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 1,
      sym_description_text_chunk,
    ACTIONS(78), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(5), 2,
      sym_link,
      aux_sym_description_repeat1,
    ACTIONS(74), 13,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [227] = 5,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 1,
      sym_name_text_chunk,
    ACTIONS(86), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(9), 2,
      sym_link,
      aux_sym_name_repeat1,
    ACTIONS(82), 13,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [256] = 5,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 1,
      sym_name_text_chunk,
    ACTIONS(95), 1,
      anon_sym_LBRACK_LBRACK,
    STATE(9), 2,
      sym_link,
      aux_sym_name_repeat1,
    ACTIONS(90), 13,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [285] = 4,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_context_repeat1,
    ACTIONS(100), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(98), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [310] = 2,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_name_text_chunk,
    ACTIONS(106), 14,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_LBRACK_LBRACK,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [331] = 4,
    ACTIONS(70), 1,
      anon_sym_R_COLON,
    STATE(28), 1,
      sym_recurrence,
    ACTIONS(110), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(108), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [356] = 4,
    ACTIONS(102), 1,
      anon_sym_COMMA,
    STATE(10), 1,
      aux_sym_context_repeat1,
    ACTIONS(114), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(112), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [381] = 2,
    ACTIONS(116), 2,
      ts_builtin_sym_end,
      sym_name_text_chunk,
    ACTIONS(118), 14,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_LBRACK_LBRACK,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [402] = 4,
    ACTIONS(124), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_context_repeat1,
    ACTIONS(122), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(120), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [427] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 15,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      sym_description_text_chunk,
      anon_sym_LBRACK_LBRACK,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [448] = 2,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    ACTIONS(118), 15,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      sym_description_text_chunk,
      anon_sym_LBRACK_LBRACK,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [469] = 2,
    ACTIONS(129), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(127), 11,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_COMMA,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [489] = 2,
    ACTIONS(133), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(131), 11,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_R_COLON,
      anon_sym_PERCENT,
      sym_id_hash,
  [509] = 2,
    ACTIONS(137), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(135), 11,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_R_COLON,
      anon_sym_PERCENT,
      sym_id_hash,
  [529] = 2,
    ACTIONS(141), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(139), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [548] = 2,
    ACTIONS(145), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(143), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [567] = 2,
    ACTIONS(149), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(147), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [586] = 2,
    ACTIONS(153), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(151), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [605] = 2,
    ACTIONS(157), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(155), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [624] = 2,
    ACTIONS(161), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(159), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [643] = 2,
    ACTIONS(165), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(163), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [662] = 2,
    ACTIONS(169), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
    ACTIONS(167), 10,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
      anon_sym_DOLLAR,
      anon_sym_BANG,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_AT,
      anon_sym_PERCENT,
      sym_id_hash,
  [681] = 5,
    ACTIONS(175), 1,
      sym_depth5_marker,
    STATE(30), 1,
      aux_sym_depth4_action_repeat1,
    STATE(38), 1,
      sym_depth5_action,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(173), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
  [701] = 5,
    ACTIONS(175), 1,
      sym_depth5_marker,
    STATE(31), 1,
      aux_sym_depth4_action_repeat1,
    STATE(38), 1,
      sym_depth5_action,
    ACTIONS(177), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(179), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
  [721] = 5,
    ACTIONS(185), 1,
      sym_depth5_marker,
    STATE(31), 1,
      aux_sym_depth4_action_repeat1,
    STATE(38), 1,
      sym_depth5_action,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(183), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
  [741] = 5,
    ACTIONS(192), 1,
      sym_depth4_marker,
    STATE(33), 1,
      aux_sym_depth3_action_repeat1,
    STATE(44), 1,
      sym_depth4_action,
    ACTIONS(188), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(190), 3,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
  [760] = 5,
    ACTIONS(192), 1,
      sym_depth4_marker,
    STATE(34), 1,
      aux_sym_depth3_action_repeat1,
    STATE(44), 1,
      sym_depth4_action,
    ACTIONS(194), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(196), 3,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
  [779] = 5,
    ACTIONS(202), 1,
      sym_depth4_marker,
    STATE(34), 1,
      aux_sym_depth3_action_repeat1,
    STATE(44), 1,
      sym_depth4_action,
    ACTIONS(198), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(200), 3,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
  [798] = 5,
    ACTIONS(209), 1,
      sym_depth3_marker,
    STATE(36), 1,
      aux_sym_depth2_action_repeat1,
    STATE(47), 1,
      sym_depth3_action,
    ACTIONS(205), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(207), 2,
      sym_depth1_marker,
      sym_depth2_marker,
  [816] = 5,
    ACTIONS(209), 1,
      sym_depth3_marker,
    STATE(37), 1,
      aux_sym_depth2_action_repeat1,
    STATE(47), 1,
      sym_depth3_action,
    ACTIONS(211), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(213), 2,
      sym_depth1_marker,
      sym_depth2_marker,
  [834] = 5,
    ACTIONS(219), 1,
      sym_depth3_marker,
    STATE(37), 1,
      aux_sym_depth2_action_repeat1,
    STATE(47), 1,
      sym_depth3_action,
    ACTIONS(215), 2,
      ts_builtin_sym_end,
      sym_state_open,
    ACTIONS(217), 2,
      sym_depth1_marker,
      sym_depth2_marker,
  [852] = 2,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
    ACTIONS(224), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
  [864] = 2,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      sym_depth5_marker,
      sym_state_open,
    ACTIONS(228), 4,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
      sym_depth4_marker,
  [876] = 5,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    ACTIONS(232), 1,
      sym_state_open,
    STATE(50), 1,
      sym_state,
    STATE(51), 1,
      sym__action_body,
    STATE(40), 2,
      sym_root_action,
      aux_sym_source_file_repeat1,
  [893] = 5,
    ACTIONS(237), 1,
      sym_depth1_marker,
    ACTIONS(239), 1,
      sym_depth2_marker,
    STATE(43), 1,
      aux_sym_depth1_action_repeat1,
    STATE(53), 1,
      sym_depth2_action,
    ACTIONS(235), 2,
      ts_builtin_sym_end,
      sym_state_open,
  [910] = 5,
    ACTIONS(243), 1,
      sym_depth1_marker,
    ACTIONS(245), 1,
      sym_depth2_marker,
    STATE(42), 1,
      aux_sym_depth1_action_repeat1,
    STATE(53), 1,
      sym_depth2_action,
    ACTIONS(241), 2,
      ts_builtin_sym_end,
      sym_state_open,
  [927] = 5,
    ACTIONS(239), 1,
      sym_depth2_marker,
    ACTIONS(250), 1,
      sym_depth1_marker,
    STATE(42), 1,
      aux_sym_depth1_action_repeat1,
    STATE(53), 1,
      sym_depth2_action,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      sym_state_open,
  [944] = 2,
    ACTIONS(252), 3,
      ts_builtin_sym_end,
      sym_depth4_marker,
      sym_state_open,
    ACTIONS(254), 3,
      sym_depth1_marker,
      sym_depth2_marker,
      sym_depth3_marker,
  [955] = 5,
    ACTIONS(5), 1,
      sym_state_open,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      sym_state,
    STATE(51), 1,
      sym__action_body,
    STATE(40), 2,
      sym_root_action,
      aux_sym_source_file_repeat1,
  [972] = 4,
    ACTIONS(260), 1,
      sym_depth1_marker,
    STATE(49), 1,
      aux_sym_root_action_repeat1,
    STATE(56), 1,
      sym_depth1_action,
    ACTIONS(258), 2,
      ts_builtin_sym_end,
      sym_state_open,
  [986] = 2,
    ACTIONS(264), 2,
      sym_depth1_marker,
      sym_depth2_marker,
    ACTIONS(262), 3,
      ts_builtin_sym_end,
      sym_depth3_marker,
      sym_state_open,
  [996] = 2,
    ACTIONS(266), 1,
      sym_state_not_started,
    ACTIONS(268), 4,
      sym_state_completed,
      sym_state_in_progress,
      sym_state_blocked,
      sym_state_cancelled,
  [1006] = 4,
    ACTIONS(272), 1,
      sym_depth1_marker,
    STATE(49), 1,
      aux_sym_root_action_repeat1,
    STATE(56), 1,
      sym_depth1_action,
    ACTIONS(270), 2,
      ts_builtin_sym_end,
      sym_state_open,
  [1020] = 4,
    ACTIONS(86), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(275), 1,
      sym_name_text_chunk,
    STATE(2), 1,
      sym_name,
    STATE(8), 2,
      sym_link,
      aux_sym_name_repeat1,
  [1034] = 4,
    ACTIONS(260), 1,
      sym_depth1_marker,
    STATE(46), 1,
      aux_sym_root_action_repeat1,
    STATE(56), 1,
      sym_depth1_action,
    ACTIONS(277), 2,
      ts_builtin_sym_end,
      sym_state_open,
  [1048] = 3,
    ACTIONS(78), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(279), 1,
      sym_description_text_chunk,
    STATE(7), 2,
      sym_link,
      aux_sym_description_repeat1,
  [1059] = 2,
    ACTIONS(283), 1,
      sym_depth1_marker,
    ACTIONS(281), 3,
      ts_builtin_sym_end,
      sym_depth2_marker,
      sym_state_open,
  [1068] = 3,
    ACTIONS(5), 1,
      sym_state_open,
    STATE(32), 1,
      sym__action_body,
    STATE(50), 1,
      sym_state,
  [1078] = 3,
    ACTIONS(285), 1,
      aux_sym_link_text_token1,
    STATE(81), 1,
      sym_link_text,
    STATE(82), 1,
      sym_link_url,
  [1088] = 1,
    ACTIONS(287), 3,
      ts_builtin_sym_end,
      sym_depth1_marker,
      sym_state_open,
  [1094] = 3,
    ACTIONS(5), 1,
      sym_state_open,
    STATE(29), 1,
      sym__action_body,
    STATE(50), 1,
      sym_state,
  [1104] = 3,
    ACTIONS(5), 1,
      sym_state_open,
    STATE(35), 1,
      sym__action_body,
    STATE(50), 1,
      sym_state,
  [1114] = 3,
    ACTIONS(5), 1,
      sym_state_open,
    STATE(39), 1,
      sym__action_body,
    STATE(50), 1,
      sym_state,
  [1124] = 3,
    ACTIONS(5), 1,
      sym_state_open,
    STATE(41), 1,
      sym__action_body,
    STATE(50), 1,
      sym_state,
  [1134] = 3,
    ACTIONS(285), 1,
      aux_sym_link_text_token1,
    STATE(79), 1,
      sym_link_url,
    STATE(83), 1,
      sym_link_text,
  [1144] = 2,
    ACTIONS(289), 1,
      anon_sym_PIPE,
    ACTIONS(291), 1,
      anon_sym_RBRACK_RBRACK,
  [1151] = 2,
    ACTIONS(293), 1,
      aux_sym_priority_token1,
    STATE(20), 1,
      sym_minutes,
  [1158] = 2,
    ACTIONS(295), 1,
      sym_name_text_chunk,
    ACTIONS(297), 1,
      anon_sym_LBRACK_LBRACK,
  [1165] = 2,
    ACTIONS(299), 1,
      aux_sym_link_text_token1,
    STATE(71), 1,
      sym_link_url,
  [1172] = 2,
    ACTIONS(299), 1,
      aux_sym_link_text_token1,
    STATE(80), 1,
      sym_link_url,
  [1179] = 1,
    ACTIONS(301), 1,
      sym_state_close,
  [1183] = 1,
    ACTIONS(303), 1,
      ts_builtin_sym_end,
  [1187] = 1,
    ACTIONS(305), 1,
      sym_tag,
  [1191] = 1,
    ACTIONS(291), 1,
      anon_sym_RBRACK_RBRACK,
  [1195] = 1,
    ACTIONS(307), 1,
      anon_sym_RBRACK_RBRACK,
  [1199] = 1,
    ACTIONS(309), 1,
      aux_sym_priority_token1,
  [1203] = 1,
    ACTIONS(311), 1,
      aux_sym_story_token1,
  [1207] = 1,
    ACTIONS(313), 1,
      sym_tag,
  [1211] = 1,
    ACTIONS(315), 1,
      sym_datetime,
  [1215] = 1,
    ACTIONS(317), 1,
      sym_datetime,
  [1219] = 1,
    ACTIONS(319), 1,
      sym_uuid_value,
  [1223] = 1,
    ACTIONS(321), 1,
      sym_rrule_content,
  [1227] = 1,
    ACTIONS(323), 1,
      anon_sym_RBRACK_RBRACK,
  [1231] = 1,
    ACTIONS(325), 1,
      anon_sym_RBRACK_RBRACK,
  [1235] = 1,
    ACTIONS(327), 1,
      anon_sym_PIPE,
  [1239] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACK_RBRACK,
  [1243] = 1,
    ACTIONS(331), 1,
      anon_sym_PIPE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 167,
  [SMALL_STATE(7)] = 198,
  [SMALL_STATE(8)] = 227,
  [SMALL_STATE(9)] = 256,
  [SMALL_STATE(10)] = 285,
  [SMALL_STATE(11)] = 310,
  [SMALL_STATE(12)] = 331,
  [SMALL_STATE(13)] = 356,
  [SMALL_STATE(14)] = 381,
  [SMALL_STATE(15)] = 402,
  [SMALL_STATE(16)] = 427,
  [SMALL_STATE(17)] = 448,
  [SMALL_STATE(18)] = 469,
  [SMALL_STATE(19)] = 489,
  [SMALL_STATE(20)] = 509,
  [SMALL_STATE(21)] = 529,
  [SMALL_STATE(22)] = 548,
  [SMALL_STATE(23)] = 567,
  [SMALL_STATE(24)] = 586,
  [SMALL_STATE(25)] = 605,
  [SMALL_STATE(26)] = 624,
  [SMALL_STATE(27)] = 643,
  [SMALL_STATE(28)] = 662,
  [SMALL_STATE(29)] = 681,
  [SMALL_STATE(30)] = 701,
  [SMALL_STATE(31)] = 721,
  [SMALL_STATE(32)] = 741,
  [SMALL_STATE(33)] = 760,
  [SMALL_STATE(34)] = 779,
  [SMALL_STATE(35)] = 798,
  [SMALL_STATE(36)] = 816,
  [SMALL_STATE(37)] = 834,
  [SMALL_STATE(38)] = 852,
  [SMALL_STATE(39)] = 864,
  [SMALL_STATE(40)] = 876,
  [SMALL_STATE(41)] = 893,
  [SMALL_STATE(42)] = 910,
  [SMALL_STATE(43)] = 927,
  [SMALL_STATE(44)] = 944,
  [SMALL_STATE(45)] = 955,
  [SMALL_STATE(46)] = 972,
  [SMALL_STATE(47)] = 986,
  [SMALL_STATE(48)] = 996,
  [SMALL_STATE(49)] = 1006,
  [SMALL_STATE(50)] = 1020,
  [SMALL_STATE(51)] = 1034,
  [SMALL_STATE(52)] = 1048,
  [SMALL_STATE(53)] = 1059,
  [SMALL_STATE(54)] = 1068,
  [SMALL_STATE(55)] = 1078,
  [SMALL_STATE(56)] = 1088,
  [SMALL_STATE(57)] = 1094,
  [SMALL_STATE(58)] = 1104,
  [SMALL_STATE(59)] = 1114,
  [SMALL_STATE(60)] = 1124,
  [SMALL_STATE(61)] = 1134,
  [SMALL_STATE(62)] = 1144,
  [SMALL_STATE(63)] = 1151,
  [SMALL_STATE(64)] = 1158,
  [SMALL_STATE(65)] = 1165,
  [SMALL_STATE(66)] = 1172,
  [SMALL_STATE(67)] = 1179,
  [SMALL_STATE(68)] = 1183,
  [SMALL_STATE(69)] = 1187,
  [SMALL_STATE(70)] = 1191,
  [SMALL_STATE(71)] = 1195,
  [SMALL_STATE(72)] = 1199,
  [SMALL_STATE(73)] = 1203,
  [SMALL_STATE(74)] = 1207,
  [SMALL_STATE(75)] = 1211,
  [SMALL_STATE(76)] = 1215,
  [SMALL_STATE(77)] = 1219,
  [SMALL_STATE(78)] = 1223,
  [SMALL_STATE(79)] = 1227,
  [SMALL_STATE(80)] = 1231,
  [SMALL_STATE(81)] = 1235,
  [SMALL_STATE(82)] = 1239,
  [SMALL_STATE(83)] = 1243,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__action_body, 2, 0, 4),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__action_body, 2, 0, 4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__action_body, 3, 0, 9),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__action_body, 3, 0, 9),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(52),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(72),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(73),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(74),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(75),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(76),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 2, 0, 18), SHIFT_REPEAT(77),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_description_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_date, 2, 0, 16),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_date, 2, 0, 16),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_description, 2, 0, 12),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_description, 2, 0, 12),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_name_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_name_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_name_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_name_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 3, 0, 19),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 3, 0, 19),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 3, 0, 11),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 3, 0, 11),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_date, 3, 0, 20),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_date, 3, 0, 20),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 2, 0, 15),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 2, 0, 15),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 22),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 22),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 24),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_context_repeat1, 2, 0, 24),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 24), SHIFT_REPEAT(69),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 23),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_context_repeat1, 2, 0, 23),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_minutes, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_minutes, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_duration, 2, 0, 25),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_duration, 2, 0, 25),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_story, 2, 0, 14),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_story, 2, 0, 14),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_date, 2, 0, 16),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_completed_date, 2, 0, 16),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_priority, 2, 0, 13),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_priority, 2, 0, 13),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id, 2, 0, 17),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id, 2, 0, 17),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__action_body_repeat1, 1, 0, 8),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__action_body_repeat1, 1, 0, 8),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_date, 3, 0, 21),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_date, 3, 0, 21),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recurrence, 2, 0, 26),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recurrence, 2, 0, 26),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_do_date, 4, 0, 27),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_do_date, 4, 0, 27),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth4_action, 2, 0, 6),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth4_action, 2, 0, 6),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth4_action, 3, 0, 10),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth4_action, 3, 0, 10),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth4_action_repeat1, 2, 0, 7),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth4_action_repeat1, 2, 0, 7),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth4_action_repeat1, 2, 0, 7), SHIFT_REPEAT(59),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth3_action, 2, 0, 6),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth3_action, 2, 0, 6),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth3_action, 3, 0, 10),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth3_action, 3, 0, 10),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth3_action_repeat1, 2, 0, 7),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth3_action_repeat1, 2, 0, 7),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth3_action_repeat1, 2, 0, 7), SHIFT_REPEAT(57),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth2_action, 2, 0, 6),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth2_action, 2, 0, 6),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth2_action, 3, 0, 10),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth2_action, 3, 0, 10),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth2_action_repeat1, 2, 0, 7),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth2_action_repeat1, 2, 0, 7),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth2_action_repeat1, 2, 0, 7), SHIFT_REPEAT(54),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth4_action_repeat1, 1, 0, 2),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth4_action_repeat1, 1, 0, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth5_action, 2, 0, 6),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth5_action, 2, 0, 6),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth1_action, 2, 0, 6),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth1_action, 2, 0, 6),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth1_action_repeat1, 2, 0, 7),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth1_action_repeat1, 2, 0, 7),
  [245] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_depth1_action_repeat1, 2, 0, 7), SHIFT_REPEAT(58),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_depth1_action, 3, 0, 10),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_depth1_action, 3, 0, 10),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth3_action_repeat1, 1, 0, 2),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth3_action_repeat1, 1, 0, 2),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 2, 0, 3),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth2_action_repeat1, 1, 0, 2),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth2_action_repeat1, 1, 0, 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_action_repeat1, 2, 0, 7),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_root_action_repeat1, 2, 0, 7), SHIFT_REPEAT(60),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_action, 1, 0, 1),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_depth1_action_repeat1, 1, 0, 2),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_depth1_action_repeat1, 1, 0, 2),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_root_action_repeat1, 1, 0, 2),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_text, 1, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_url, 1, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state, 3, 0, 5),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_state, 3, 0, 5),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [303] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_actions(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "actions",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
